shapely/shapely

- setup.py
New custom install command fails if we can't locate a GEOS shared library (using same method as in shapely/geos.py).
Closes #218.
> Require GEOS to be preinstalled.

- .travis.yml
The trick mentioned at https://mail.python.org/pipermail/cython-devel/2014-November/004263.html cut our test time from 30 to 12 mins :)
Definitely worth a merge and some updates to sibling projects.
> Try work around suggested at

- shapely/ctypes_declarations.py
- shapely/geos.py
- tests/test_geos_err_handler.py
Tests for the error and notice handlers, which was buggy, and fixes for the bugs.
There's still some major fragility here. See my comments above the handler functions in shapely/geos.py.
This PR replaces #247
> Tested error handler

- shapely/geos.py
- tests/test_operations.py
> Relate errcheck

- docs/manual.rst
- shapely/ctypes_declarations.py
- shapely/geometry/base.py
- shapely/geos.py
- shapely/impl.py
- tests/test_predicates.py
> Relate pattern

- shapely/ctypes_declarations.py
- shapely/geometry/multipolygon.py
- tests/test_empty_polygons.py
> Ensure empty multipolygons when args are empty

- shapely/geometry/base.py
> Use type() in __eq__() instead of isinstance()

- tests/test_linestring.py
> Added test for LineString/LinearRing equals order issue.

- shapely/geos.py
Because they're going to be static from now on.
Closes #374.
> Don't reuse rasterio/fiona's GEOS shared libs on OS X

- shapely/geos.py
> Support frozen apps on Windows

- shapely/geometry/base.py
> Fixed memory leak when copying/unpickling geometries.

- .gitignore
- .travis.yml
- setup.cfg
- setup.py
Ready for review.  Any problems with enabling coveralls and adding a badge to the readme?
- Add support for `$ pip install -e .[test]` and `$ pip install -e .[all]`
- Update `.gitignore`
- Move to Travis's newer container-based infrastructure
> Small updates to dev setup and testing

- shapely/geos.py
> Do not configure logger

- setup.py
In this case, CFLAGS and LDFLAGS must be set.
Resolves #322
Obsoletes #417
> geos-config call is skipped if NO_GEOS_CONFIG env is set

- shapely/geometry/geo.py
- tests/test_collection.py
Hello,
I added support for `GeometryCollection` to the `shape` and `asShape` functions. Hope it can help other people.
By the way, great package! Thank you!
*PS: I would very much appreciate if you could tag the issue with [hacktoberfest](https://hacktoberfest.digitalocean.com/)* 😄
> Add support for GeometryCollection to shape and asShape functions

- shapely/coords.py
- shapely/geometry/linestring.py
- shapely/geometry/multipoint.py
- shapely/geometry/point.py
- shapely/geometry/polygon.py
- shapely/speedups/_speedups.pyx
- tests/test_ndarrays.py
The final touches on removing our accidental hard dependency on Numpy.
> Move access to coords via array protocol entirely to speedups

- shapely/geometry/linestring.py
- shapely/geometry/point.py
- tests/test_linestring.py
- tests/test_point.py
> Implemented array interface for empty Point and LineString.

- shapely/geos.py
- tests/test_geos_err_handler.py
Also some code and docstring cleanup.
Resolves #447
> Change log level for GEOS notice handler to 'info'

- README.rst
Just fixed coda-forge link, was formatted for markup not rst.
(Also, I'm sorry if I messed up the commit/pull process. First time.)
> Small link correction

- CHANGES.txt
- shapely/geos.py
> Reduce CDLL'ing log level to debug

- shapely/geometry/point.py
- tests/test_point.py
> Raise TypeError if Point is init with > 3 args

- docs/manual.rst
> Added documentation for CoordinateSequence

- shapely/geometry/base.py
> Make the meanings of equality more explicit in docstrings

- docs/manual.rst
I didn't see any notes on how contributions should be formatted, so I hope this is an acceptable pull-request.
Please let me know if you have any thoughts or suggestions on wording/content.
> Added details to R-tree documentation

- shapely/prepared.py
- shapely/topology.py
> Tighten prepared geometry validation condition

- .travis.yml
This fixes the build errors in the master branch.
I didn't mean to create this branch in the main repository - need to remove after merge.
> Added --upgrade flag to pip install in travis.yml

- docs/manual.rst
- shapely/affinity.py
> DOC: Correction to order in matrix multiplication

- docs/manual.rst
- shapely/affinity.py
> DOC: Correction to transpose in matrix multiplication

- shapely/geos.py
- tests/test_geos_err_handler.py
fix for https://github.com/Toblerity/Shapely/issues/695
> #695: fix segfault and unicode errors for non text parameter wkt loads

- shapely/geometry/polygon.py
- shapely/speedups/_speedups.pyx
- tests/test_polygon.py
Fix for https://github.com/Toblerity/Shapely/issues/706
> Construct Polygon from Points

- shapely/geos.py
> Load GEOS only once in the wheel case

- setup.py
This helps packagers downstream b/c they can just remove the .c files and they will be auto-regenerated. (This is common practice for to re-cythonize when packaging.)
> Simplify force_cython logic

- docs/manual.rst
Addresses https://github.com/Toblerity/Shapely/issues/749.
> DOC: Update references to python2 print statements in user manual

- docs/manual.rst
> Add a pyproj Transformer example

- shapely/affinity.py
- tests/test_affinity.py
Fixes #793, and similar potential issue with skew.
> Avoid in-place multiplication of affinity parameters

- CHANGES.txt
- shapely/geometry/base.py
> bool(geom) shall be the logical complement of geom.is_empty

- shapely/_geos.pxi
- shapely/geometry/polygon.py
- shapely/speedups/_speedups.pyx
- tests/test_polygon.py
> raise ValueError if LinearRing is made with invalid LineString

- shapely/ops.py
When start_dist > end_dist, the first/last points where disordered
> Fix misorderded points in substrings

- docs/manual.rst
* Tweak docs - make `is_ring` description more precise
> Tweak docs - make `is_ring` description more precise

- shapely/geometry/geo.py
- tests/test_collection.py
- tests/test_shape.py
Fixes https://github.com/Toblerity/Shapely/issues/837
Fixes https://github.com/Toblerity/Shapely/issues/840
Two questions:
- I wasn't sure about more tests, but I'm not opposed to adding a `test_shape.py`
- Does this logic also need to support `asShape`? It wasn't super clear to me how that should work.
> Handle for empty list/list of lists in 'coordinates'

- docs/manual.rst
I've update the docs for the STRtree in manual.rst. This should close these issues (#854, #845, #618) and one other pull request (https://github.com/Toblerity/Shapely/pull/623). Note that I have not done anything with the docstrings. I think I would like to work on that in a separate merge later. Maybe waiting to close those issues until that is done as well is a good idea. 
Also note that I have changed the work around for getting indexes to use an auxiliary dictionary keyed on geometry memory IDs instead of adding an index attribute to the geometries themselves (or a deep copy if you don't want to mutate.) 
Compare: 
``` python 
>>> from copy import deepcopy
>>> 
>>> points = [Point(i, i) for i in range(10)]
>>> tree = STRtree(points)
>>>
>>> points_numbered = []
>>> for i, point in …
```
> Strtree docs

- .travis.yml
- appveyor.yml
- ci/travis/install_geos.sh
Also with Travis CI, build and run tests
> Update GEOS to 3.8.1

- docs/manual.rst
> add documentation for minimum clearance property

- shapely/geometry/geo.py
> Improve docstrings for shape, asShape, and mapping

- docs/manual.rst
See https://github.com/Toblerity/Shapely/blob/c613520bc4a1fce667a18ac14ef95de62677c093/shapely/strtree.py#L95
> Fix documentation typo

- docs/manual.rst
> update overlaps docs to more closely match Wikipedia / JTS

- docs/manual.rst
Addressing #903. I feel like this is a good start, but I'm not sure if the intention of the issue was also to add docstrings to the methods? Happy to do that too if it's desired.
> Document set-like properties

- shapely/ctypes_declarations.py
I used > instead of >= for the GEOS version, resulting in a bug. Sorry about that.
> Fix makevalid GEOS version

- shapely/ctypes_declarations.py
- shapely/geometry/base.py
- shapely/geos.py
- shapely/impl.py
- tests/test_predicates.py
Adding support for GEOSCoveredBy. See geopandas - https://github.com/geopandas/geopandas/issues/1452
> Add support for GEOSCoveredBy 

- CHANGES.txt
- shapely/geometry/base.py
> Correct test in empty()

- tests/test_polygon.py
Similarly as #963, but now for LinearRing/Polygon tests
>  TST: clean-up + more cases for LinearRing/POlygon constructor tests

- .travis.yml
- setup.cfg
- shapely/geometry/base.py
- shapely/geometry/collection.py
- shapely/geometry/geo.py
- shapely/geometry/multipoint.py
- shapely/geometry/multipolygon.py
- shapely/geometry/point.py
> Fix doctests, run in CI

- shapely/coords.py
- shapely/geometry/base.py
- shapely/speedups/_speedups.pyx
- tests/test_linestring.py
- tests/test_point.py
- tests/test_polygon.py
> Return empty CoordinateSequence instead of list

- docs/manual.rst
> DOC: Version of the minimum_clearance function

- CHANGES.txt
- shapely/strtree.py
- tests/test_strtree.py
- tests/test_strtree_nearest.py
> Warn about upcoming STRtree changes

- setup.cfg
> Wheels are only universal if they support Python 2 & 3

- shapely/geometry/base.py
> Fix tiny spelling errors in BaseGeometry

- CHANGES.txt
- shapely/coords.py
- shapely/geometry/base.py
- shapely/geometry/linestring.py
- shapely/geometry/point.py
- shapely/geometry/polygon.py
- tests/test_polygon.py
Fixes the issue reported in https://github.com/geopandas/geopandas/issues/1943.
> Never pass empty geometries to GEOS_getCoordSeq

- tests/test_minimum_rotated_rectangle.py
removed duplicate instance type check
> Removed duplicate line in test_minimum_rotated_rectangle.py

- docs/migration.rst
Small follow-up on https://github.com/Toblerity/Shapely/pull/1180
> DOC: small sphinx fixes for the migration guide

- CHANGES.txt
- appveyor.yml
- shapely/geometry/base.py
- shapely/geometry/conftest.py
- shapely/vectorized/__init__.py
- tests/conftest.py
Here's the fix for #1184, supersedes #1191.
> import speedups from vectorized

- CITATION.txt
- CREDITS.txt
- README.rst
- docs/manual.rst
- setup.py
- tests/test_polylabel.py
- tests/test_union.py
This is very similar to #1255 but for the shapely-1.8 maintenance branch.
> Replace Toblerity/Shapely -> shapely/shapely

- shapely/__init__.py
- shapely/tests/geometry/test_collection.py
- shapely/tests/geometry/test_coords.py
- shapely/tests/geometry/test_emptiness.py
- shapely/tests/geometry/test_geometry_base.py
- shapely/tests/geometry/test_hash.py
- shapely/tests/geometry/test_linestring.py
- shapely/tests/geometry/test_multilinestring.py
- shapely/tests/geometry/test_multipoint.py
- shapely/tests/geometry/test_multipolygon.py
- shapely/tests/geometry/test_point.py
- shapely/tests/geometry/test_polygon.py
xref discussion in https://github.com/shapely/shapely/issues/1330
> Expose the geometry subclasses in the top-level namespace

- .pre-commit-config.yaml
- shapely/geometry/base.py
- shapely/ops.py
- shapely/tests/test_measurement.py
See https://github.com/psf/black/issues/2964
> CI: update black to fix click compat issue

- src/geos.c
- src/geos.h
> Clean the NoticeHandler

- .github/workflows/release.yml
See #1348 for discussion.
If this works on maint-1.8 I'll submit the same PR to main.
@kvashchuka @mwtoews @sgillies @jorisvandenbossche
> Add Python 3.10 wheels for additional platforms

- .travis.yml
Attempt to fix the tests on Travis
> CI: fix Travis tests

- .github/workflows/release.yml
- .github/workflows/tests.yml
- .travis.yml
- docker/Dockerfile.valgrind
See https://lists.osgeo.org/pipermail/geos-devel/2022-June/010685.html
> CI: upgrade GEOS patch versions for tests and release

- shapely/geometry/base.py
- shapely/tests/geometry/test_emptiness.py
- shapely/tests/geometry/test_point.py
Closes https://github.com/shapely/shapely/issues/1023
> API: change the bounds of an empty geometry from empty tuple to tuple of NaNs

- shapely/ctypes_declarations.py
- shapely/geometry/base.py
> BUG: destroy GEOSBufferParams to avoid memory leak

- shapely/affinity.py
- tests/test_affinity.py
This is an idea borrowed from @ThomasHilger in https://github.com/shapely/shapely/discussions/1336
> PERF: use numpy matmul for affine transformation

- README.rst
Small left-over that I didn't fix in https://github.com/shapely/shapely/pull/1378
> DOC: fix repr in example

- shapely/geometry/base.py
- shapely/tests/geometry/test_geometry_base.py
> [ENH] Add reverse method to BaseGeometry

- CHANGES.txt
- shapely/__init__.py
- shapely/strtree.py
- tests/test_strtree.py
> Revert removal of strtree deprecation warning

- .github/workflows/tests.yml
- shapely/ctypes_declarations.py
- shapely/geometry/base.py
- shapely/geometry/collection.py
- shapely/geometry/multilinestring.py
- shapely/geometry/multipoint.py
- shapely/geometry/multipolygon.py
- shapely/geometry/polygon.py
- shapely/ops.py
In an attempt to fix the issue reported in #1449 and perhaps solved in https://github.com/django/django/pull/15214.
> Replace c_void_p with c_geom_p

- shapely/ctypes_declarations.py
- shapely/geometry/base.py
- shapely/geometry/collection.py
- shapely/geometry/multilinestring.py
- shapely/geometry/multipoint.py
- shapely/geometry/multipolygon.py
- shapely/geometry/polygon.py
- shapely/ops.py
- shapely/strtree.py
- shapely/topology.py
Reverts shapely/shapely#1479, which didn't fix the issue it intended to fix.
> Revert "Replace c_void_p with c_geom_p"

- tests/test_affinity.py
- tests/test_box.py
- tests/test_buffer.py
- tests/test_cga.py
- tests/test_delaunay.py
- tests/test_equality.py
- tests/test_geointerface.py
- tests/test_invalid_geometries.py
- tests/test_linear_referencing.py
> TST: rewrite tests using pytest assert

- shapely/tests/test_set_operations.py
- src/ufuncs.c
> Fix segfault in reduction functions

- CHANGES.txt
- shapely/constructive.py
- shapely/geometry/base.py
- shapely/tests/geometry/test_geometry_base.py
- shapely/tests/test_constructive.py
- Renamed parameter
- Updated function description
- Updated tests
Closes https://github.com/shapely/shapely/issues/1454
> Update segmentize tolerance parameter to max segment length

- shapely/geometry/base.py
- shapely/tests/geometry/test_geometry_base.py
xref https://github.com/shapely/shapely/issues/1281
> ENH: expose dwithin on the Geometry subclasses

- shapely/geos.py
> add _lgeos to darwin frozen app check

- tests/test_create_inconsistent_dimensionality.py
> TST: change WKT tests with inconsistent dimensionality for GEOS 3.12

- docs/index.rst
- docs/migration_pygeos.rst
Closes #1500
@caspervdw @brendan-ward a review especially of the STRtree changes would be welcome
> DOC: add migration guide for PyGEOS users

- .travis.yml
Follow-up on https://github.com/shapely/shapely/pull/1561
> CI: update cibuildwheel version in travis as well

- docs/manual.rst
The `release` variable is already correctly specified in `conf.py`
> DOC: automatically fill in correct version

- shapely/geometry/base.py
- shapely/geometry/polygon.py
- shapely/tests/geometry/test_geometry_base.py
Closes https://github.com/shapely/shapely/issues/1588
> ENH: allow Geometry methods to return arrays if passed array as argument

- shapely/geometry/base.py
- shapely/tests/geometry/test_geometry_base.py
xref https://github.com/shapely/shapely/issues/1281
> ENH: expose contains_properly on the Geometry subclasses

- shapely/predicates.py
xref https://github.com/shapely/shapely/issues/1521#issuecomment-1327483015
> DOC: add note about prepare + touches to contains_xy/intersects_xy docstrings

- shapely/constructive.py
> DOC: fix default for preserve_topology in simplify docstring

- shapely/geometry/polygon.py
- shapely/tests/geometry/test_polygon.py
Closes https://github.com/shapely/shapely/issues/1662
> REGR: fix Polygon() constructor from sequence of Points

- docs/manual.rst
- shapely/ops.py
- tests/test_polygonize.py
Closes https://github.com/shapely/shapely/issues/1691
> DOC: fix cuts/dangles result order in polygonize_full docs

- shapely/creation.py
> DOC: Improve docstring for prepared

- CREDITS.txt
- shapely/geometry/linestring.py
- shapely/geometry/point.py
- shapely/geometry/polygon.py
- shapely/tests/geometry/test_decimal.py
- shapely/tests/geometry/test_point.py
> BUG: geometry constructors now support `Decimal` inputs

- docs/release/2.x.rst
> DOC: 2.x.rst - Add API REFERENCE link

- shapely/constructive.py
- shapely/ops.py
shapely/ops.py, shapely/constructive.py - `snap`: merge documentation and examples and examples and add some more details from `libgeos` docs.
> DOC: `snap`: merge documentation and examples from `ops` and `constructive`

- shapely/tests/test_set_operations.py
Upstream changes via https://github.com/libgeos/geos/commit/bd42a68a09ae9001a66ad4e1a82cd563639ef30b change `coverage_union*` behavior in a few ways:
1. Overlapping polygons don't raise an error, but a mostly unchanged output is returned.
2. It has the undocumented ability of unioning linear networks.
3. Point types are currently accepted, but will likely throw an error before GEOS 3.12 is finalized.
Xref https://github.com/libgeos/geos/issues/904
> TST: update for coverageUnionNG behavior

- .github/workflows/tests.yml
- CHANGES.txt
- shapely/coordinates.py
- shapely/tests/test_coordinates.py
Port 'interleaved' and auto-z detection from PR #1676
> Port 'interleaved' and auto-z detection from PR 1676

- docs/environment.yml
- pyproject.toml
- shapely/_geos.pyx
This should fix the error reported in https://github.com/conda-forge/shapely-feedstock/pull/125#issuecomment-1682266283 and observed in https://github.com/shapely/shapely/pull/1858
> Fix for cython 3 compatibility

- shapely/prepared.py
- shapely/tests/legacy/test_prepared.py
Use the exposed geos function now, as it has been exposed now. Also resolves #1875.
> CLN: Use exposed `contains_properly` for `PreparedGeometry`

- .github/workflows/tests.yml
First part of https://github.com/shapely/shapely/issues/1972, to start with testing running numpy 2.0.dev
> TST: test against numpy nightly

- CHANGES.txt
- docs/release/2.x.rst
See https://github.com/shapely/shapely/issues/1742#issuecomment-1938773084
> DOC/RLS: starts changelog for 2.0.3

- .github/workflows/release.yml
See https://github.com/scientific-python/upload-nightly-action/issues/63
> Upload nightly wheels to Scientific Python nightly channel

- .circleci/config.yml
See https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
> BLD: update circleci image for arm wheel building

- shapely/geometry/point.py
- shapely/tests/geometry/test_point.py
Closes https://github.com/shapely/shapely/issues/2070
> BUG: fix Point x/y/z/m attribtues to return Python floats

- shapely/creation.py
- shapely/set_operations.py
Forgot about this in https://github.com/shapely/shapely/pull/1982/
> DOC: add versionadded to new disjoint_subset_union docstring

- CHANGES.txt
- shapely/constructive.py
- shapely/measurement.py
- shapely/tests/test_constructive.py
- src/ufuncs.c
> ENH: add function minimum_clearance_line

- shapely/_geometry.py
- shapely/_ragged_array.py
- shapely/geometry/base.py
- shapely/predicates.py
Apply final round of feedback on PR #2104 (after it was merged).
> MAINT: apply pydocstyle followup

- CHANGES.txt
- shapely/geos.py
- shapely/tests/geometry/test_format.py
- shapely/tests/legacy/__init__.py
- shapely/tests/legacy/test_create_inconsistent_dimensionality.py
- shapely/tests/legacy/test_pickle.py
> DEPR: deprecate the shapely.geos module

- docs/manual.rst
The existing example code does not show how to use loads method.
> DOC: update wkt/wkb loads examples

- .circleci/config.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- pyproject.toml
Copying over a few small updates from the main branch in preparation of https://github.com/shapely/shapely/issues/2208
> MAINT: update CI (cibuildwheel, tested version) on maint branch

- .github/workflows/release.yml
- CHANGES.txt
- CITATION.cff
- docs/conf.py
- docs/release/2.x.rst
> Release 2.0.7

- shapely/_ragged_array.py
- shapely/tests/test_ragged_array.py
Closes https://github.com/shapely/shapely/issues/1794
> ERR: Add better error message for (not) providing offsets in from_ragged_array

- shapely/constructive.py
- shapely/geometry/base.py
> DOC: clarify that polygon returned in oriented_envelope is not normalized

- CONTRIBUTING.md
I wanted to get the introduction in first before starting on the details of how to contribute. The project has done a poor job of explaining what kind of contributions are welcome, and that's the most important thing to fix.
> Very rough start of a contributing doc

- shapely/_geometry_helpers.pyx
- shapely/_ragged_array.py
Follow-up on https://github.com/shapely/shapely/pull/2142,  now doing the same for MultiLineStrings
> PERF: speed up from_ragged_array for MultiLineStrings

- shapely/_geometry_helpers.pyx
- shapely/_geos.pxd
- shapely/geometry/polygon.py
- shapely/tests/test_io.py
Closes https://github.com/shapely/shapely/issues/2005
> BUG: preserve M values for pickle roundtrip of LinearRing

- src/ufuncs.c
Two small fixes getting rid of a build warning
> CLN: fix build warning in ufuncs.c

- docs/code/coverage_simplify.py
- docs/environment.yml
- docs/release/2.x.rst
Adding a code example to the M values section, and adding a dedicated section for the coverage functions with an illustration with the countries of Africa.
> DOC: expand release notes new features section

- CHANGES.txt
- CITATION.cff
- docs/release/2.x.rst
Preparing for release later today
> RLS: 2.1.0

- shapely/_geometry_helpers.pyx
> BUG: Add casts to GEOSGeom_destroy_r and GEOSGeom_createPolygon_r.

- FAQ.rst
Inspired by https://github.com/shapely/shapely/issues/2308. This really is a frequently asked question.
> DOC: add topic about robustness of intersects to the FAQ
