shapely/shapely

build-scripts/macosx-10.6-intel.sh
shapely/geos.py

4 lines added to shapely/geos.py will let us load a shared library included in a [binary wheel for OS X](https://github.com/MacPython/wiki/wiki/Spinning-wheels). This means a completely self-contained Shapely wheel that "just works" on a OS X system Python or python.org Python.
My plan is to use [delocate](https://github.com/matthew-brett/delocate) to copy dependencies and relink the extension modules as the SciPy project does. Currently, I'm using the Kyngchaos Framework libs because they are dual architecture (like python.org's Python). It brings the wheel size up to 1.2MB, which isn't too bad at all.
@mwtoews can you review this for me and merge? I'd like to get a binary wheel for 1.5.2 out for some user testing soon.

Making OS X binary wheels that include a GEOS dylib

---

setup.py

When Cythonizing fails, setup.py throws an exception since the wrong `build_ext` is used. See the following:
```
$ python setup.py build_ext --inplace
Updating C extension with Cython.
running build_ext
...
command 'gcc' failed with exit status 1
Warning: The C extension could not be compiled, speedups are not enabled.
Failure information, if any, is above.
I'm retrying the build without the C extension now.
running build_ext
File "setup.py", line 298, in <module>
setup(**setup_args)
File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
dist.run_commands()
File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
self.run_command(cmd)
File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
cmd_obj.run()
File …
```

On later attempt to build_ext, remove previously added cython_build_ext

---

setup.py

My previous version checking is messing up others' builds. See #234. I propose to revert e12d1d2 here in maint (the 1.5.x release branch) and try to fix in master using PR #239.

Revert "Require GEOS to be preinstalled."

---

setup.py
shapely/geos.py
shapely/libgeos.py
tests/__init__.py
tests/test_dlls.py

The main thing done here is to move the system-dependant loading of the GEOS dynamic library into a separate module `shapely.libgeos`, which can be used by setup.py for checking versions before install, and by `shapely.geos` for run-time use the GEOS of dynamic library.
A TODO item is to figure out a different way to specify the dynamic library (#234). Someone else might need to take the lead on this, but at least it will be in one place, rather than repeated in `setup.py` and `shapely/geos.py`. CC @kynan for ideas.
Secondly, `geos-config`, where available, is used to obtain libraries and headers for developing Cython extensions. This is useful where GEOS is installed on a non-standard prefix. An alternative location for this utility can be proved for setup.py using a `GEOS_CONFIG` …

Move system-dependant logic to load dynamic library into minimal module, and use geos-config to get development headers

---

shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py
tests/test_svg.py

To `.svg()`
* 1 element per geometry
* multi-part geometries are grouped in `<g>...</g>` elements
* empty geometries are `<g />`
To `._repr_svg_()`
* add the basic attributes to the the svg element (xmlns et al.) to show output in, e.g. Firefox; see http://www-archive.mozilla.org/projects/svg/faq.html#source
* empty geometries are `<svg ... />`
Also, the second parameter is either `color`, `fill_color`, or `stroke_color`, depending on the geometry type. When this is `None`, it is determined if the geometry is valid, as before. (I'm open to just calling this `color`).
Unit testing is added to ensure consistency of output, and only XML is validated (I don't know of an SVG validator).
Fixes #233.

Modify svg() and _repr_svg_() outputs

---

README.rst
setup.py
shapely/libgeos.py

The first method is borrowed from #240 / GeoDjango, which is to use an
environment variable GEOS_LIBRARY_PATH to point directly to a dynamic library.
If this seems like a hack, it can be removed. However, it could be useful
for folks that don't have GEOS_CONFIG, such as Windows, and want to use a
different DLL file.
The second method is to use geos-config from the PATH, or can be explicity set
using a GEOS_CONFIG flag. It attempts a few paths to libraries from the output
from `geos-config --clibs`. If used in combination with GEOS_LIBRARY_PATH,
the two library versions are checked by setup.py.
After these attempts, the old code is still in place (with very minor changes).
An unused `free` object is still a TODO.
This is a continuation of #239.

Load dynamic library using two alternative methods

---

shapely/impl.py
tests/test_default_impl.py

Add an ImplementationError, akin to but slightly different from NotImplementedError. It also derives from KeyError and AttributeError for backwards compatibility with code that catches those errors for this particular case.    
This one would close #216.

Add ImplementationError

---

shapely/geometry/multipoint.py

`MultiPoint([])` should work like `MultiPolygon([])`.

Allow creation of  multipoint from empty list

---

shapely/geos.py

We're using pyinstaller to generate binaries, but the binaries generated on Darwin have a different directory structure than py2app.  This proposed change would simply add support for pyinstaller-generated binaries to be able to locate the GEOS dylib.
Happy to discuss, and thanks for the awesome library!

Updating for pyinstaller paths

---

shapely/libgeos.py

It seems that ctypes.util.find_library doesn't always find libc on Mac OS X Yosemite.
```
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('c')
>>>
```
```
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  5 2014, 20:42:22) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('c')
>>
```
This patch puts the full path of the file in the fallbacks to work around this problem.

fallback for darwin on load_dll('c')

---

shapely/geometry/base.py
tests/__init__.py
tests/test_multi.py
tests/test_multilinestring.py
tests/test_multipoint.py
tests/test_multipolygon.py

Use numbers.Integral to allow for more robust integer index check.
Fixes #266

Fix int check in GeometrySequence.__getitem__

---

shapely/ctypes_declarations.py
shapely/geometry/linestring.py
shapely/geos.py
tests/test_parallel_offset.py

This PR switches to using `GEOSOffsetCurve` instead of `GEOSSingleSidedBuffer` which was deprecated in GEOS 3.3.0. Existing code shouldn't notice any change, although the requirement that the `distance` parameter be positive has been removed; instead, if the distance is negative the `side` parameter is inverted. The `side` parameter is now optional, as it can be defined implicitly by the polarity of `distance`. This is all handled in `geos.py` to keep version specific details outside of `linestring.py`.
https://github.com/libgeos/libgeos/blob/aa57155d18f8cbb33b5090c5ea4bae349abf4db2/capi/geos_ts_c.cpp#L1800

Use OffsetCurve instead of SingleSidedBuffer in GEOS >= 3.3

---

shapely/_geos.pxi
shapely/speedups/_speedups.pyx

As https://github.com/Toblerity/Shapely/pull/276, but PR for the `maint` branch for inclusion with 1.5.9.
Original PR as follows:
This PR addresses three warnings currently being raised by the speedups module.
It implements the change from https://github.com/Toblerity/Shapely/pull/274 using `uintptr_t` instead of `unsigned long long`.
It fixes the warning below, by using the `unsigned int` type for the `m` dimension variable to `GEOSCoordSeq_getSize_r`.
```
shapely/speedups/_speedups.c:3210:58: warning: passing 'int *' to parameter of
type 'unsigned int *' converts between pointers to integer types with
different sign [-Wpointer-sign]
GEOSCoordSeq_getSize_r(__pyx_v_handle, __pyx_v_cs, (&__pyx_v_m));
^~~~~~~~~~~~
```
It also removes some of the other warnings being raised by the speedups …

Cython warnings (maint branch)

---

.travis.yml
docs/manual.rst
shapely/geometry/__init__.py
shapely/geos.py
shapely/speedups/__init__.py
tests/conftest.py

This PR addresses the issue(s) raised in https://github.com/Toblerity/Shapely/issues/251
* Fixed a minor bug in `shapely.speedups.disable`
* Enable Cython speedups by default, if available
For instance:
```
>>> import shapely.speedups
>>> shapely.speedups.enabled
True
```
Tests should be called --with-speedups or --without-speedups - this has been amended in `.travis.yml`.
The manual has been updated to reflect the changes.
I've assumed this would be included in 1.6, rather than 1.5.x, although I'm not sure now. Certainly the first commit should be cherry picked into the 1.5 branch. I feel this is worth some good testing, as if it is broken it would break everything.

Enable Cython speedups by default (if available)

---

requirements-dev.txt
shapely/vectorized/_vectorized.pyx
tests/test_vectorized.py

I regularly use a CentOS 6 server with NumPy 1.4.1 (released 22 Apr 2010), which is [the current version](http://mirror.centos.org/centos/6/os/x86_64/Packages/). This PR drops the minimum-supported NumPy version and has a few modifications to enable py.test to pass with speedups enabled.
Here is the specific rational for the changes:
* The `copy` keyword for `astype()` was introduced in 1.7.0 (e.g. see [ndarray.astype(t)](http://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.astype.html#numpy.ndarray.astype) from Numpy 1.6.0)
* Before 1.6.0, `copy()` only supported positional arguments, and `order='f'` would raise "TypeError: copy() takes no keyword arguments"; see [bug #2178](https://github.com/numpy/numpy/issues/2178)
* The modification to the cdef bool result array is …

Allow tests to work with NumPy 1.4.1

---

tests/test_dlls.py
tests/test_locale.py

* there are no .so files in win32
* resetlocale() raises exception on windows http://bugs.python.org/issue10466

Fix tests on windows:

---

shapely/geometry/base.py
shapely/geometry/polygon.py
tests/test_hash.py

Shapely's geometries are mutable, but we're providing a hash function. These two features are inconsistent. Rather than remove mutability (for now) we'll remove the hashability.
See #209

Make geometries unhashable

---

setup.py

With the current master, running `python setup.py install` gives
TypeError: unorderable types: Version() >= tuple()
on the shapely version check, but this change seems to fix it. That's on Python 3.4.

Fix shapely version check

---

shapely/strtree.py
tests/test_strtree.py

This PR fixes the issue with empty geometries and STRtree in #345.
I think I've done the right thing aiming this at the maint-1.5 branch but correct me if I've done it wrong?

Filter empty geometries in STRtree to avoid segfaults. Fixes #345.

---

shapely/geometry/polygon.py
tests/test_polygon.py

This PR fixes a bug triggered when comparing the equality of empty Polygons. The accompanying test illustrates the issue. The problem is that an empty polygon doesn't have any coordinates, so `self.exterior.coords` in the existing algorithm falls over.

Fix for equals comparison with empty polygons

---

shapely/geometry/base.py
tests/test_minimum_rotated_rectangle.py

I tried adding the functionality requested in #354  to enhance the base geometry object. 
This function enables the computation of a minimum bounding rectangle that is not constrained to be parallel to the axes but can be rotated.
The solution is based on the algorithm proposed in this [link](http://gis.stackexchange.com/questions/22895/how-to-find-the-minimum-area-rectangle-for-given-points/22934#22934) that was provided by @snorfalorpagus

Add minimum_rotated_rectangle function.

---

docs/manual.rst
shapely/ctypes_declarations.py
shapely/geos.py
shapely/ops.py
tests/test_shared_paths.py

This PR implements the GEOSSharedPaths operation, which arrived in GEOS 3.3.x.
The function finds shared parts between two lineal geometries.
I've implemented this as `shapely.ops.shared_paths` rather than `LineString.shared_paths`. An argument could be made for either I guess.

Implemented GEOSSharedPaths.

---

docs/manual.rst
shapely/ctypes_declarations.py
shapely/geometry/base.py
shapely/geos.py
shapely/impl.py
tests/test_operations.py

This PR implements GEOHausdorffDistance. In simple terms the hausdorff distance is the furthest distance between any point on one geometry to any point on another.
https://en.wikipedia.org/wiki/Hausdorff_distance
Available in GEOS 3.2.x.

Implemented GEOSHausdorffDistance

---

docs/code/minimum_rotated_rectangle.py
docs/manual.rst

Added documentation for geometry.minimum_rotated_rectangle in the manual, as requested in issue #364. I tried adding a figure too.

Add docs for minimum_rotated_rectangle

---

shapely/_geos.pxi

This PR fixes #372.
This kind of change has already been made in `_speedups.pyx`, but hadn't been applied to `_geos.pxi`.

Use uintptr_t to store pointers instead of long in _geos.pxi

---

shapely/geos.py

PyInstaller's OSX-specific bug fix that add an additional fallback path to geos_c library using _MEIPASS related to https://github.com/HDFGroup/hdf-compass/issues/79

PyInstaller's OS X-specific bug fix

---

shapely/prepared.py

It's not possible to pickle a prepared geometry. It doesn't look like there is any way to get the original representation of the geometry from the prepared one from GEOS, so I think it's better to explicitly forbid pickling. The following code demonstrates the issue, causing a segmentation fault when the unpickled instance tries to access the GEOS geometry that has been destroyed.
```
from shapely.geometry import Point
from shapely.prepared import prep
import pickle
p1 = Point(1,2)
p2 = prep(p1)
data = pickle.dumps(p2)
del(p2)
p3 = pickle.loads(data)
p3.intersects(p1)  # segmentation fault
```
(Why you'd want to pickle a prepared geometry I don't know, but better safe than sorry?)

Raise PicklingError when attempting to pickle a prepared geometry.

---

.dockerignore
.gitignore
Dockerfile.wheels
build-linux-wheels.sh
shapely/geos.py

This patch uses Docker and [auditwheel][] to build [manylinux1][] wheels for Python 2.6/3.3+. These wheels bundle GEOS into the wheel, similar to the OS X wheels, so Shapely can be `pip install`d on most Linuxes without GEOS or even a compiler.
All of the wheels are built with one step: `./build-linux-wheels.sh`.  This will build a Docker image based on the official manylinux images containing GEOS and will build all of the wheels and output them in `wheels/`. Note that this only builds x86_64 wheels, but it could be easily extended to building i686 wheels using the quay.io/pypa/manylinux1_i686 Docker image.
[auditwheel]: https://github.com/pypa/auditwheel
[manylinux1]: https://github.com/pypa/manylinux

Build manylinux1 wheels

---

shapely/geometry/polygon.py
tests/test_polygon.py

Ready for review.
To support patterns like:
```python
import fiona
from shapely.geometry import Polygon
with fiona.open('input.shp') as src:
bounds = Polygon.from_bounds(*src.bounds)
```

Polygon.from_bounds()

---

shapely/geometry/linestring.py
shapely/geometry/polygon.py
shapely/speedups/_speedups.pyx
tests/test_emptiness.py

This PR enables the creation of empty geometries, by passing a zero-length list (or other iterable), e.g:
```line = LineString([])```
Fixes #397.

Instancing geometries with an empty list returns an empty geom.

---

shapely/_buildcfg.py
shapely/geos.py

This PR resolves #343 by changing the library name on Windows from `geos.dll` (the C++ library) to `geos_c.dll` (the C library, needed by ctypes).
I've tested this on a fresh install of OSGeo4W.
I normally use Shapely on Windows via conda, which makes this change in it's build also: https://github.com/conda-forge/shapely-feedstock/blob/master/recipe/geos_c.patch
@pelson Presumably this change will break the current shapely-feedstock patch.

Look for geos_c.dll not geos.dll on Windows. Fixes #343.

---

CHANGES.txt

The spelling error was noticed while reviewing the changes in 1.6a1 as part of the Debian package update.

Fix 'defualt' typo, replace with 'default'

---

shapely/geos.py
tests/test_dlls.py

This PR adds the paths used by the Anaconda Python distribution to the fallback paths when loading the GEOS shared library. Closes #401.
I've aimed this at `maint-1.6` - hopefully this is correct.

Added library search path for Anaconda

---

setup.cfg

From the changelog of [pytest v. 3.0.0](http://doc.pytest.org/en/latest/changelog.html#id21)
> [pytest] sections in setup.cfg files should now be named [tool:pytest] to avoid conflicts with other distutils commands (see #567). [pytest] sections in pytest.ini or tox.ini files are supported and unchanged.

Fix pytest warning about [pytest] in setup.cfg

---

docs/manual.rst

Three times ``geoms`` vs one `geoms`
Three times ``list()`` vs one :func:`list`

minor formatting consistency

---

docs/manual.rst

wkt dumps/loads example was missing the import
(made a pull request on my fork instead of this earlier on accident...)

add missing import

---

docs/code/buffer.py
docs/code/cascaded_union.py
docs/code/convex_hull.py
docs/code/difference.py
docs/code/figures.py
docs/code/geometrycollection.py
docs/code/intersection-sym-difference.py
docs/code/linearring.py
docs/code/linestring.py
docs/code/minimum_rotated_rectangle.py
docs/code/multilinestring.py
docs/code/multipolygon.py
docs/code/parallel_offset.py
docs/code/parallel_offset_mitre.py
docs/code/polygon.py
docs/code/polygon2.py
docs/code/rotate.py
docs/code/scale.py
docs/code/simplify.py
docs/code/skew.py
docs/code/triangulate.py
docs/code/union.py

This PR adds support for Python 3.x rendering of the documentation figures (as mentioned in #337). It also removes some code duplication by moving common functions into `figures.py`. More could probably be done, but this will do for now.

Improvements to documentation figures

---

.travis.yml
setup.py
shapely/coords.py
tests/conftest.py
tests/test_vectorized.py

This is a WIP but could benefit from some comments.
- Tests running shapely on Travis without numpy (#431).
- Fixes a bug preventing shapely running without numpy (also #431).
- Removes support for Python 2.6 on Travis (#432).
- Expands the build matrix used by Travis to be more verbose. This gives more control over what is tested. There is now a `SPEEDUPS=0/1` and `NUMPY=0/1` variable. This could also provide an `AUTODOC=0/1` variable for use in #337.
- The test requirements for test_vectorized.py have been modified. Previously they ran if numpy was present. We distribute .c files for speedups.pyx and vectorized.pyx, in case the user doesn't have cython installed. I think it's more likely that the user doesn't have a C compiler installed, in which case the .c files aren't much use. The …

Changes to travis.yml and support for running without numpy

---

tests/test_linestring.py

Misuse of `assert` like a function resulted in a warning from pytest, this fixes it and also removes trailing whitespace from the file.

Fix bad assert in test_numpy in test_linestring.py

---

shapely/geometry/linestring.py
shapely/speedups/_speedups.pyx
tests/test_linestring.py

Prevent segfault when attempting to create LineString with only one coordinate tuple.
Added a specific check for inputs with len() < 2, but also added
a more generic catch for createLineString/LinearRing returning
a NULL pointer.
Closes #486. Credit to @clement-tourriere for an excellent report.

Prevent segfault when attempting to create LineString with only one coordinate tuple.

---

shapely/speedups/_speedups.pyx

This is a small change to affine_transform that fixes #493. Add z values to x and y when doing 3D transforms, consistent with the documentation for affine_transform.

quick fix to affine_transform

---

environment.yml
readthedocs.yml

In the same spirit as https://github.com/Toblerity/Fiona/pull/466 and encouraged by the discussion on https://github.com/Toblerity/Fiona/issues/258, I made a similar pull request to build Shapely docs on Read the Docs. You can see the result here:
http://juanlu001-shapely.readthedocs.io/en/latest/
Closes #337.

Build docs on Read the Docs

---

shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/point.py
shapely/geometry/polygon.py
shapely/geometry/proxy.py
shapely/iterops.py
shapely/ops.py
shapely/predicates.py
shapely/validation.py

Thank you for this incredibly useful module! `shapely` is as fun to use as it is powerful.
I was reading through the source code tonight to try to gain a deeper understanding of what's going on, and found a few unused imports in some modules. Please consider this PR to remove them.

Remove some unused imports

---

shapely/geometry/base.py
tests/test_emptiness.py

This provides an explicit means of creating an empty geometry object. Motivated by desire for a clear empty geometry type to use in na operations in geopandas. Thanks @sgillies for laying this out in #513, and @jorisvandenbossche for motivation in #510.
I went with `EmptyGeometry`, rather than `Empty`, thinking it made the context slightly clearer when used outside of `shapely`. I created an `__init__` mainly for the docstring, while retaining the `BaseGeometry` docstring for the class; maybe that's not necessary though?

Add EmptyGeometry class

---

shapely/geos.py

@sgillies I hope this is OK for your coding standards. This PR modifies `geos.py` to find the `conda` `geos` lib first, if `shapely` is in a conda env, and then tries to find the system libs.
This should not affect `wheels` or `frozen`  packages. The only pathological case I can imagine is if someone installed `shapely` with `conda` but expects it to find the system libs, which is a really bad idea but still possible if someone uninstalls the `conda` `geos`.
xref: https://github.com/conda-forge/shapely-feedstock/pull/28
ping @dopplershift and @Chilipp who are interested in this.

patch to find conda geos first

---

shapely/geometry/base.py

Fixes "`Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method MultiPolygon.__del__ of <shapely.geometry.multipolygon.MultiPolygon object at 0x2b074e819590>>'"
Likely also related to https://github.com/Toblerity/Shapely/issues/473

catch TypeError in BaseGeometry.empty

---

docs/manual.rst

Connected to #526 and #500
Here I fix the wrong definition of the Polygon constructor in the user manual.
Also, the documentation about the "Attributes" (https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/polygon.py#L196) seems to me a bit unclear and redundant with the user manual. However I don't know the policy of this repo about documentation.

Fix user manual (geometry.Polygon)

---

.travis.yml

Replaced Python 3.5 with 3.6 on Travis. We're testing 3.4 already.

Added Python 3.6 to Travis tests

---

shapely/strtree.py

There are some circumstances in which CPython can call `__del__` on an object twice. For me, that was happening when running a script under [`python-flamegraph`](https://github.com/evanhempel/python-flamegraph). This is because it runs a separate thread which is walking the stack, causing it to keep a reference to the `STRtree` object and attempt to delete it twice.

Don't double-free in STRtree's __del__ if it is called multiple times.

---

docs/manual.rst

Add a note about the set-theoretic methods always returning a geometry and how to treat that in conditions. Ref https://github.com/Toblerity/Shapely/issues/77
I have no idea if the reference syntax is correct, please verify that!
Also, I am just _assuming_ that what I say is actually true :o)

set theoretic methods always return a geometry

---

shapely/geometry/polygon.py
tests/test_pickle.py

This PR fixes the issue identified in #547.
Geometries are pickled using the WKB format, which does not differentiate between LINESTRING and LINEARRING objects. When a LinearRing is pickled/unpickled the result is a Shapely LinearRing with a GEOS LineString inside, which can lead to issues later. This change works around the problem by copying the coordinate sequence of the geometry after it's read from WKB into the correct geometry type. It's slightly frustrating that we have to clone the sequence, but it's required due to GEOS's ownership model.

Fixed bug in unpickling of LinearRing. Closes #547.

---

shapely/geos.py

In a PyInstaller frozen application the libraries are placed in the same directory as the main executable (`bin`). PyInstaller creates a `sys._MEIPASS` attribute to point to this directory. Without this change running an application from anywhere other than the `bin` directory results in an exception for not finding the geos library.
I previously thought fixing this would require a change to @ocefpaf's conda-based changes in #521 but it seems like `CONDA_PREFIX` isn't set in a pyinstaller frozen application.

Fix finding libgeos on windows in pyinstaller frozen application

---

docs/manual.rst

On http://locationtech.github.io/jts/ the link to "LocationTech home page" is given as https://www.locationtech.org/projects/technology.jts
The current links are 404.

Fixed 404 hyperlinks to JTS webpage

---

.travis.yml
README.rst
_vendor/packaging/markers.py
_vendor/packaging/requirements.py
_vendor/packaging/specifiers.py
_vendor/packaging/version.py
setup.py
shapely/_buildcfg.py
shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/geometry/polygon.py
shapely/geos.py
tests/__init__.py
tests/test_delaunay.py

Python 2.6 was already removed (see https://github.com/Toblerity/Shapely/issues/432 and https://github.com/Toblerity/Shapely/pull/433), this removes some redundant 2.6 code, and adds use of automatic formatters which are available since Python 2.7.
https://github.com/Toblerity/Shapely/issues/432 also mentions Python 3.3 is coming up to EOL, and since 2017-09-29 it now is EOL. So remove that too.
https://devguide.python.org/#status-of-python-branches
As a check, here's the pip installs for Shapely from PyPI for last month, showing very little use with 2.6 and 3.3:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.5            |  72.37% |        390,258 |
| 2.7            |  23.32% |        125,757 |
| 3.6            |   2.73% |         14,735 | …

Update Python versions

---

docs/manual.rst

Couldn't find the old wiki referenced anywhere, sorry if I overlooked it.

gispython.org is dead, this removes references to it

---

shapely/geometry/geo.py
tests/test_mapping.py

In the current code, if you try to save and parse an empty polygon, the shape() method will result in an IndexError.
```python
from shapely.geometry import Polygon, shape, mapping
shape(mapping(Polygon()))
File "...", line 2910, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-3-305ea9043881>", line 1, in <module>
shape(mapping(Polygon()))
File ".../python3.5/site-packages/shapely/geometry/geo.py", line 35, in shape
return Polygon(ob["coordinates"][0], ob["coordinates"][1:])
IndexError: tuple index out of range 
```
This pull request aim to resolve this issue with a simple Try/Except

shape() method can parse empty geojson

---

shapely/ctypes_declarations.py
shapely/geos.py
shapely/ops.py
tests/test_clip_by_rect.py

TODO - write docstring.
@drnextgis - is there a good reference for this?
> This function from GEOS 3.5.0. Clips a geometry by a 2D box in a fast but possibly dirty way.
Closes #370.

Added GEOSClipByRect / shapely.ops.clip_by_rect

---

CHANGES.txt
shapely/wkb.py
tests/test_wkb.py

Added the `srid` keyword argument to `wkb.dumps` to include an SRID in WKB data, as suggested in #592.
I've added some tests for WKB in `test_wkb.py` (to match `test_wkt.py`). There are already some in `test_persist.py` which I've left alone. Perhaps this could be expanded in the future, but it's not essential.
An observation is that `pickle` uses `wkb.dumps` to store data. This defaults to not exporting the SRID (even if one is present in the geometry after loading with `loads`. This means that the round-trip for a geometry with an SRID isn't perfect. However I think this is acceptable as generally we're ignoring the SRID in Shapely.

Added srid keyword to wkb.dumps. Closes #592.

---

setup.py

While (accidentally) attempting to build Shapely on an old computer with Python 2.6, I found an incomprehensible error:
```
File "setup.py", line 167, in <module>
fp.write(str(shapely_version))
File "/home/mtoews/src/Shapely/_vendor/packaging/version.py", line 252, in __str__
parts.append(".post{}".format(self._version.post[1]))
ValueError: zero length field name in format
```
This PR provides a clearer message:
> RuntimeError: Shapely requires Python 2.7, >=3.4

Add a runtime Python version check in setup.py

---

docs/manual.rst

* https where available (tested!).
* also updated JTS URLs to where they go redirected/migrated to.
* could not find a recent URL for http://www.vividsolutions.com/jts/discussion.htm#spatialDataModel (not in https://github.com/locationtech/jts/tree/gh-pages/), so I pointed it to IA's latest: https://web.archive.org/web/20160719195511/http://www.vividsolutions.com/jts/discussion.htm.

https all the links, plus updates

---

shapely/speedups/_speedups.pyx
tests/test_polygon.py

Fixed bug in creating LinearRing from LineString. Closes #609.
Only triggered when using speedups (cython) and numpy.
`LinearRing(line)` now works identically to `LinearRing(line.coords[:])`.
Maintaining 4 different versions of the same code (python/cython with/without numpy) is a pain, but I'm not sure how we can make it any better.

Fixed bug in creating LinearRing from LineString. Closes #609.

---

shapely/algorithms/polylabel.py
tests/test_polylabel.py

This PR adds a special case for rectangular polygons to the polylabel algorithm, present in the original JavaScript version. See https://github.com/mapbox/polylabel/issues/3

Avoid floating point error for rectangular polygons in polylabel.

---

shapely/geometry/base.py
tests/test_delaunay.py
tests/test_operations.py

This PR addresses #653 by adding an `exceptNull` decorator to `interpolate`, thereby preventing segmentation faults when attempting to interpolate a `Point` along a `LINESTRING EMPTY` object and failing gracefully.
* initial commit is a simple correction of 2 test case in `tests/test_delaunay.py` which were failing
-------------
```
=============================================================== warnings summary ================================================================
tests/test_delaunay.py::DelaunayTriangulation::test_lines
/Users/jgaboardi/Shapely/tests/test_delaunay.py:28: DeprecationWarning: Please use assertTrue instead.
self.assert_(isinstance(p, LineString))
/Users/jgaboardi/Shapely/tests/test_delaunay.py:28: DeprecationWarning: Please use assertTrue instead. …
```

correcting bug in interpolate (issue #653)

---

tests/test_substring.py

Adding edge case (no pun intended...) to test that internal coordinates are preserved when cutting to either end of line.
Addressed by #658 and #659

add ops.substring test for edge case: endpoint geoms with internal coords

---

shapely/ops.py

If `min_dist` is equal to 0 (i.e. the first coordinate) then the loop immediately breaks.
This means that internal coordinates are skipped because only `(start_point.x, start_point.y)` and `(end_point.x, end_point.y)` are written to the new `vertex_list`.
By changing the less than to a less-than-equal sign the loop behaves as intended.

Fixing bug in ops.substring

---

docs/manual.rst

I was reading the docs and saw that `cascaded_union` is still more prominently explained than `unary_union`, and I was assuming you should now prefer to use `unary_union` over `cascaded_union`, so therefore I switched them in order (long explanation for `unary_union`, and then short one for `cascaded_union` referring to the other, instead of the other way around now).
But then I saw in the code that for more recent versions of GEOS, they are actually simply an alias, and `cascaded_union` is not using the old cascaded union implementation any more. So maybe `unary_union` is not necessarily "recommended" over `cascaded_union`?

DOC: switch cascaded_union and unary_union

---

shapely/ops.py
tests/test_split.py

This PR fixes the `split_line_with_point` function for closed rings where the point falls in the last segment.
This needs review - there is a lot of indexing and slices are hard!

Rewrite of function to split line by point. Fixes #585.

---

shapely/geometry/multipoint.py

Fix a typo: replace `instaces` by `instances` in the `MultiPoint.__init__` docstring.

DOC: fix typo in MultiPoint.__init__ docstring

---

.travis.yml

23 days until Python 3.4 end of life.  https://docs.python.org/devguide/index.html#branchstatus
Also, [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

Travis CI: Upgrade from Python 3.4 --> 3.5

---

docs/manual.rst

Explain how left and right of parallel offset is determined. See issue #692

Update documentation of parallel offset

---

docs/manual.rst

The manual describes Hausdorff distance as follows:
>.. method:: object.hausdorff_distance(other)
>
>  Returns the Hausdorff distance (``float``) to the `other` geometric object.
>  The Hausdorff distance is the furthest distance from any point on the first
>  geometry to any point on the second geometry.
>
>  `New in Shapely 1.6.0`
Depending on how one interpreted this description, this would suggest that the following code would return either a 4 or a 1 when it fact it returns a 2 (as it should).
```
A = LineString([(0,0),(2,0)])
B = LineString([(1,0),(4,0)])
A.hausdorff_distance(B)
```
As it is, the documentation implies that Hausdorff distance can be described mathematically as either:
$\sup_{x \in A, y \in B}d(x,y)$
or at a stretch
$\sup_{x \in A}\inf_{y \in B}d(x,y)$
rather than …

Correct the description of Hausdorff distance

---

docs/code/unary_union.py
docs/manual.rst
shapely/examples/dissolve.py
shapely/examples/intersect.py
shapely/ops.py

- Brief info about what happens with different kinds of geometries (via
https://geos.osgeo.org/doxygen/classgeos_1_1operation_1_1geounion_1_1UnaryUnionOp.html)
- Extend doc example with validity of MultiPolygon
- Demote cascaded_union from being worthy of mention
- Fix GEOS version in note
- Update plot generation from cascaded to unary
- Update examples from cascaded to unary
- "Hypier" and more abstract section title

Replace cascaded with unary union in docs and more

---

shapely/geometry/point.py
tests/test_point.py

The `.bounds` method of an empty point should return an empty tuple, the same as it does for other geomety types. Without this fix an `IndexError` is raised when the method tries to access the zeroth coordinate which doesn't exist.
I've used the pytest style syntax for the test, but the rest of the test module is still using the older unittest syntax.
Fun fact: the existing behaviour is 9 years old.

Bounds of an empty point is an empty tuple. Fixes #716

---

shapely/geometry/polygon.py
tests/test_polygon.py

Fix for https://github.com/Toblerity/Shapely/issues/712 as was suggested by @sgillies.

Exterior of an empty polygon is equivalent to LinearRing()

---

shapely/affinity.py

Made changes in Docstrings to avoid "invalid escape sequence" DeprecationWarnings with Python 3.6

Fix invalid scape sequence warning

---

shapely/geos.py

With reference to https://github.com/Toblerity/Shapely/issues/394, this was the same problem that happened to me. The root cause is because `find_library("c")` returns something empty for certain linux environments. Searching through some of these forums, it looks like this won't be fixed. As such, we have to accommodate this on the package side. 
My environment only had the following `libc` libraries:
```
./lib/libc.musl-x86_64.so.1
./usr/glibc-compat/lib/libc.so.6
./usr/glibc-compat/lib/libc.so
```
The fix below adds the path for `./lib/libc.musl-x86_64.so.1`. I've tested this and it solved the issue.

Add fallback path for libc.musl

---

CREDITS.txt
README.rst
docs/manual.rst

* Removes unused references at the end of `manual.rst`
* Updates some URLs to use https
* Fixes a footnote reference (previously unreferenced)
* Switched one link to use a reference instead but the remaining links seemed fine as is
I noticed that `design.rst` is not used. Should that file be removed? 
Also, the ToC has an entry for `API Documentation <modules>` that goes unused, it looks like because `make apidocs` is still outputting txt files. Should that get updated to rst or should that entry just get removed?
Resolves #617

Cleanup References

---

shapely/_buildcfg.py

Allow fallback for loading libc.so.6 
i'm having issue in mock for linux environment to build this package but with allowing fallback for libc.so.6 i was able to pass the build
File "setup.py", line 80, in <module>
from shapely._buildcfg import geos_version_string, geos_version, \
File "/builddir/build/BUILD/Shapely-1.6.4.post2/shapely/_buildcfg.py", line 168, in <module>
free = load_dll('c').free
File "/builddir/build/BUILD/Shapely-1.6.4.post2/shapely/_buildcfg.py", line 161, in load_dll
libname, fallbacks or []))
OSError: Could not find library c or load any of its variants []

In linux env add fallback load dll for libc.so.6

---

shapely/affinity.py
tests/test_affinity.py

`affine_transform` checks if empty but the functions in affinity will raise an Exception before reaching that check as noted in #763. This resolves #763

Guard for empty geometries in affinity functions

---

tests/test_operations.py

Simple fix to a test issue identified in https://github.com/conda-forge/shapely-feedstock/pull/58 and fixes #799
This change is related to new behaviour for `POINT EMPTY` with GEOS 3.8.0
See also #742 for a recent discussion on empty geometry handling, and I'll re-iterate that PR #352 (not merged) is still a good patch that should be revised to handle how GEOS and modern PostGIS work.

Change intersection test to check is_empty

---

shapely/ctypes_declarations.py
shapely/geometry/base.py
shapely/geos.py
shapely/impl.py
tests/test_buffer.py

Attempting to add support for single sided buffers raised in this issue: https://github.com/Toblerity/Shapely/issues/727

Implement GEOSBufferParams to support single sided buffers.

---

shapely/_buildcfg.py
shapely/geos.py

I just get an error when I install QGIS 'vector tile plugin' into macOS with homebrew.
QGIS3 can't find path and use [this search path](https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L128) but it doesn't include homebrew path.

added homebrew path for supports QGIS3 for macOS

---

shapely/ops.py

https://github.com/Toblerity/Shapely/commit/053df248e4663c8a0f800a4c03e80521a28e8f2e causes an encoding error for Python 2.7 because of the fancy quote. This just replaces it with a dumb one.
This fixes the build failures in the other PRs.

Small fix to encoding for Python 2.7

---

shapely/algorithms/polylabel.py
tests/test_polylabel.py

The existing implementation of `polylabel` does not properly account for interior holes in the polygon, as the original algorithm does.
Closes #817.

Fix polylabel for polygons with holes

---

environment.yml

Fixes the failing doc builds: https://readthedocs.org/projects/shapely/builds/10532936/.
Docs here: https://shapely.readthedocs.io/en/rtd-memory-reduction/index.html.

Simplify RTD conda env

---

docs/manual.rst

Additions: 
1. Mention right side reversal (#785)  
2. Break up parameter descriptions into paragraphs  
3. Italicize parameters (``)  
4. Link buffer method where the docs for *resolution* parameter are outsourced to it.  
5. Improved explanation of the *mitre_limit* parameter.
6. Warn that a MultiLineString may be returned where a simple LineString is expected (#746)
Reservations:  
1. Breaking up the parameter descriptions into paragraphs makes it consistent. But maybe harder to read because of some very short paragraphs? 
2. Perhaps a warning about #746 is too heavy.  
Could be better: 
1. An example of how to post-process in the case of a MultiLineString where a LineString is expected to get the LineString you want. Perhaps there is a simple solution to this that could rely on …

Parallel offset docs

---

shapely/ops.py

`ops.split` of a polygon by line is slow on big polygons with many holes,
because of the many `poly.contains` operations needed after polygonize
This simply prepares the polygon to speed-up greatly those operations.
The overhead for little to no holes cases is minimal.
See attached a [profiling script](https://github.com/Toblerity/Shapely/files/4360331/shapely_split_pr_profile.zip) on two cases: 100 smalls polygons, and 1 big polygon (those are real geometries coming from satellite images).
Summary of script  output: 
```
original: collection of 100 small polygons (min 4, mean 15, max 49 points, no holes)
42367 function calls in 0.112 seconds
...
original: one big polygon (total 105 183 points) with 585 holes
50387 function calls in 49.933 seconds
...
with prep(): collection of 100 small …
```

Fix _split_polygon_with_line performance for big polygons with many holes

---

.travis.yml

In https://github.com/Toblerity/Shapely/pull/870 we're seeing signs that we're not using the GEOS versions we expect when we run the tests.

Set library paths in our CI environment

---

shapely/strtree.py

Here are some docstrings for the strtree module. They're in the numpydoc style. Even though shapely does not do that yet, @sgillies mentioned that sometime he would like to take them in that direction. I guess my thinking is that it can be done incrementally. You can checkout the auto generated documentation from them here: https://jeremiah-england.github.io/shapely/test-numpydocs/docs/build/index.html 
Let me know if you see any issues. One question that may to come up is that ugly
```rst
.. autoclass:: STRtree
:members:
```  
in the middle of the module docstring. I'm auto generating the class documentation in the middle of the module docstring so the reference goes at the end. I'm not super attached to that if someone wants me to change it though. 
doctest and rst check out.

strtree docstrings

---

.travis.yml
_vendor/packaging/_compat.py
_vendor/packaging/markers.py
_vendor/packaging/specifiers.py
setup.py
shapely/_buildcfg.py
shapely/coords.py
shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py
shapely/geos.py
shapely/ops.py
shapely/speedups/_speedups.pyx
shapely/vectorized/_vectorized.pyx
tests/test_geos_err_handler.py
tests/test_ndarrays.py
tests/test_persist.py
tests/test_pickle.py

* Minimum Python version 3.5
* Simplify/remove if-blocks that handled Python 2 or 3 logic
* No more izip or xrange
* Set cython: language_level=3
* Rearrange setup() kwargs for distutils or setuptools
Closes #743

Drop Python 2.7 and Python 2 related logic and functions

---

docs/manual.rst
shapely/ops.py

This should address both #878 and #826. The docs now reflect the updated API in `pyproj >= 2.1`, demonstrate use of `Transformer` and `CRS`; show clearly and call out the necessity of `always_xy` per #878; and include the classic example using older versions of `pyproj`. I also changed the order of the examples to show the more current behavior of `pyproj` first.

Update the docs and docstrings for transform

---

shapely/geos.py

Per #888 
`load_dll('c').free` fail on Darwin, without MacPort or Homebrew, because libc is not found on my system.
By default, on Mac, `libc` is provided by `libSystem.dylib`.
A robust solution is to replace `load_dll('c').free` by `CDLL(None).free` because Python is already using libc.
>     CDLL(None) internally calls dlopen(NULL), and as the dlopen
>     manpage says, "If filename is NULL, then the returned handle is for the
>     # main program". This way we can let the linker do the work to figure out
>     # which libc Python is actually using.
>

Load libc on darwin in any cases

---

docs/code/voronoi_diagram.py
docs/manual.rst
shapely/ctypes_declarations.py
shapely/geos.py
shapely/ops.py
tests/test_voronoi_diagram.py

Per #833. 
I thought it made sense to keep Delauney / Voronoi close together in the code since they're similar in use and right next to each other in the CAPI, but if you disagree I'm happy to move it to wherever.
I couldn't nail down for sure exactly when VoronoiDiagram was added to the CAPI. [This](https://github.com/libgeos/geos/blob/master/NEWS#L167) entry was the best I could find indicating release version, so I went with 3.5.0.

Add GEOSVoronoiDiagram to shapely

---

shapely/strtree.py
tests/conftest.py
tests/test_strtree.py

Fix for #830.
I couldn't really replicate this issue on macos, but [this merge request](https://github.com/Toblerity/Shapely/pull/528) fixed a very similar issue in basically the same way, and [`PreparedGeometry`](https://github.com/Toblerity/Shapely/blob/de4838e102dcfd54aadc8af03ed33def918334e6/shapely/prepared.py#L36) has a guard against the same thing, so it seems like it is a known situation where shapely's geos handle has been disposed of before python has cleaned up other Shapely objects.
For completeness I checked all the other `__del__` methods in Shapely and it looks like this is the last unguarded one. 
I switched the tests for `STRtree` from `unittest` to `pytest` because it seems like tests are moving in that direction and I thought I'd do it while I was in there, but if …

Guard against calling methods on lgeos after it's been cleaned up

---

shapely/errors.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
tests/test_multilinestring.py
tests/test_multipoint.py

Closes #836.
As of Shapely 1.7, asking for the WKT of a MultiPoint or -LineString with an empty component results in a segfault. I figured it made more sense to error in that case and let the user take care of the issue - realistically I can't see much utility in having a MultiPoint or -LineString with an empty component anyway, and I don't think you can create such a geometry through WKT, WKB, or GeoJSON, so it doesn't make sense to allow it through the geometry object constructor, either.

Raise an error on creation of MultiPoint or LineString with empty components

---

shapely/geos.py

I have multiples different environments and diferents IDEs. When I was in VScode without conda, I had the following error:
```
from MTSPTW.algorithm.clustering import Clustering...
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
c:\Users\alberto.rubiales\Desktop\projects\MTSPTW\prueba_test.py in 
----> 1 from MTSPTW.algorithm.clustering import Clustering
c:\Users\alberto.rubiales\Desktop\projects\MTSPTW\MTSPTW\algorithm\clustering.py in 
2 from pandas import concat, DataFrame
3 from sklearn.cluster import KMeans
----> 4 from geopandas import datasets, read_file
5 from shapely.geometry import Point
6 import matplotlib.cm as color_maps …
```

Problems with VScode users and multiples environments

---

docs/manual.rst
shapely/wkt.py

Adds some more detail to docs around WKT serializiation, addressing #910. Also adds docstrings to `wkt.dump` and `wkt.dumps` to explicitly list available keyword arguments.

Update docs re: WKT serialization

---

shapely/strtree.py
tests/test_strtree.py
tests/unpickle-strtree.py

GEOS STRtree handle was not excluded when pickling Python STRtree. When unpickled in another process it would become a dangling pointer and segfault.

Fix segfault when using unpickled STRtree in another process

---

shapely/geometry/geo.py
shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py
shapely/ops.py
tests/test_collection.py
tests/test_create_inconsistent_dimensionality.py
tests/test_emptiness.py
tests/test_geointerface.py
tests/test_linestring.py
tests/test_multilinestring.py
tests/test_multipoint.py
tests/test_multipolygon.py
tests/test_ndarrays.py
tests/test_point.py
tests/test_polygon.py

Deprecating the adapter classes that create geometry-like proxy objects with coordinates stored in external objects (xref https://github.com/shapely/shapely-rfc/pull/1/).
I again started with the Point geometry to check if the workflow looks good. 
There are however multiple ways to create those objects. For points, you have the general `asShape` and `asPoint`, but in principle also the `PointAdapter` class constructor (but I don't know whether those are regarded as public API?). 
The way I did it now is to add a deprecation warning to both `asShape` and `asPoint`, so the message can be specific. Bu there are certainly other ways to do it as well.

Deprecate asShape (CachingGeometryProxy adapter classes)

---

.travis.yml

This should be testing with Python 3.9.0 beta 4. See [PEP 596](https://www.python.org/dev/peps/pep-0596/), where Python 3.9 is expected to be released October 2020.
See related #944

Replace Python 3.8-dev with Python 3.9-dev

---

tests/test_collection.py

We're about to experience a good bit of churn with the push to Shapely 2.0 & merge with PyGEOS, so this seemed like a good time to work on increasing test coverage, especially in the geometry classes where I expect we will be trying to keep the interface and behavior identical while completely changing the internal workings. I also would like to consolidate tests to use Pytest, as it seems like most new tests have been written using that framework, and I think it'd be nice to have more consistency there.
If you're a 👍 on this, I'll keep adding to this or open another PR for more work, whatever is preferred. If not, no worries, but I wanted to check in to see what other folks thought before I did too much.

Increase test coverage for GeometryCollection class

---

shapely/coords.py
shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/geometry/multipoint.py
shapely/geometry/point.py
shapely/geometry/polygon.py
shapely/speedups/__init__.py
shapely/speedups/_speedups.pyx
tests/test_coords.py
tests/test_geomseq.py
tests/test_linestring.py
tests/test_multipoint.py
tests/test_point.py
tests/test_polygon.py

Deprecating the ctypes attribute and the array_interface.
See https://github.com/shapely/shapely-rfc/pull/1/files#diff-554e526a1f0fe104169383c013e37a7cR360 for the rationale
The array interface is kept intact for the CoordinateSequence, so occurence of `np.array(geom)` can be replaced with `np.array(geom.coords)`. 
(we should eventually implement this differently (not using ctypes), but that can be left for later or even for Shapely 2.0)

Deprecate ctypes attribute and array interface

---

tests/test_linestring.py
tests/test_point.py

While refactoring the class constructors based on pygeos, I noticed that not all cases that are currently supported are fully covered by the tests (eg generator, single-element list for Point, ...). So I added some more tests, and at once cleaned up the existing constructor tests.

TST: clean-up + more cases for Point/LineString constructor tests

---

shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/geometry/point.py
shapely/geometry/polygon.py
tests/test_linestring.py
tests/test_point.py
tests/test_polygon.py

I branched off from master, so the shapely-2.0 branch first needs to be reset to master state for this to work (the actual commit is only the last one)

[2.0] Remove mutability of geometries 

---

shapely/geometry/base.py

I noticed that those functions and methods are already deprecated for many years. So I think those can already be removed for 1.8, but of course, since we are removing a bunch of things in 2.0, we can also directly keep this removal for 2.0 as well (in which case I can edit the PR to target the shapely-2.0 branch instead of master)

CLN: remove deprecated to_wkb/to_wkt methods

---

shapely/geometry/base.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/ops.py
tests/test_make_valid.py
tests/test_ndarrays.py
tests/test_polygonize.py
tests/test_shared_paths.py
tests/test_voronoi_diagram.py

This should help with actually deprecating it in https://github.com/Toblerity/Shapely/pull/950

Replace internal usage of Multi geom iteration with .geoms attribute

---

.travis.yml
appveyor.yml
ci/appveyor/build_geos.cmd
ci/travis/install_geos.sh
setup.py

* Change AppVeyor image from 2017 to Visual Studio 2019
* Rename environment variable `GEOSVERSION` -> `GEOS_VERSION`
* Rename environment variable `GEOSINSTALL` -> `GEOS_INSTALL`
* Rename other local environment variables
Several of these renames are for consistency and to harmonize with pygeos and wheel-building repos.

Add Python 3.9 support to setup.py and CI

---

.travis.yml
appveyor.yml

This is an amendment to #1011 which initially passed all CI tests before merge, but subsequently raised a new AppVeyor failure with pip on Python 3.9 after merge, as `wheel` was not installed (despite it being part of `requirements-dev.txt`). This installs/upgrades `wheel` before other dependencies to avoid the issue.

TST: 'pip install wheel' before other dependencies

---

shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/geometry/point.py
shapely/geometry/polygon.py
tests/test_emptiness.py

I suppose this is more like an internal method in practice, but it's still publicly exposed, so worth officially deprecating (since it will go away in Shapely 2.0, where geometries are no longer mutable).

Deprecate the geometry .empty() method

---

shapely/geometry/base.py
shapely/geometry/collection.py
shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py
tests/test_emptiness.py

Related to https://github.com/Toblerity/Shapely/issues/999, but regardless the naming discussion / which properties we keep, the ability to *set* them from python is something that will go away in Shapely 2.0, so this PR is explicitly deprecating that.

Deprecate setting of _geom attribute

---

docs/conf.py
docs/manual.rst
shapely/ops.py
tests/test_split.py
tests/test_union.py

Resolves #1001 to deprecate `ops.cascaded_union` for Shapely 1.8.

Deprecate ops.cascaded_union, as it was superseded by ops.unary_union

---

shapely/prepared.py
shapely/vectorized/__init__.py

In PyGEOS, the GEOSPreparedGeometry is now stored on the same python extension type (C struct) as used for the base Geometry class (and there are functions to (un)prepare a geometry object "in place"). If an object is prepared, the predicate functions will automatically use it.
So in the future, we can make this interface in Shapely easier, but on the short term, I refactored the existing shapely PreparedGeometry to use the prepared functionality of PyGEOS. 
(since there is not yet an alternative for this in Shapely 1.8, so we can't deprecate this yet (if we would want that long term), and keep a working version initially in Shapely 2.0)

Refactor shapely.prepared to use prepared base geometries

---

shapely/iterops.py
shapely/topology.py
tests/test_iterops.py

Follow up on https://github.com/Toblerity/Shapely/pull/1052 (in theory a precursor, though ;))

Deprecate the shapely.iterops module

---

.github/workflows/tests.yml

Update the `maint-1.7` branch with the latest GEOS version for testing with GitHub Actions. Also tidy a minor component of the "Install python dependencies" step.

CI: bump versions to latest GEOS-3.9.1 (maint-1.7 branch)

---

.github/workflows/tests.yml
appveyor.yml
ci/install_geos.cmd

GEOS 3.9.1 was recently [announced](https://lists.osgeo.org/pipermail/geos-devel/2021-February/010138.html). Bump the following GEOS versions:
- Github Actions: 3.9.0 -> 3.9.1
- AppVeyor: 3.9.0beta2 -> 3.9.1; also, resume `ctest` build check

CI: bump versions to latest GEOS-3.9.1

---

shapely/strtree.py

Previous initialization was creating a tree with all geometries on a single leaf node.
See: https://gis.stackexchange.com/questions/353619/shapely-with-rtree-versus-strtree

Initialize STRtree with capacity of 10 items per leaf node

---

docs/manual.rst

The `.covers()` binary predicate was [added 6 years ago](https://github.com/Toblerity/Shapely/commit/0090e5de2bedfeeaeae4061cf5fd20ef88d03c88#diff-0cfd418bbccae3cd182953f575a205d0bc8bde442f40041187b6016668cbefdeR619-R621), and the `.covered_by()` binary predicate was [added last year](https://github.com/Toblerity/Shapely/commit/0ecc21c0aaef478dbfdc55bcf3b6e90a039e4b64#diff-0cfd418bbccae3cd182953f575a205d0bc8bde442f40041187b6016668cbefdeR735-R738), but neither are included in the documentation. The only way someone would know to use this is by being familiar with the DE-9IM named predicates or perusing the source code. Let's fix that.

[documentation] add `covers` and `covered_by`

---

shapely/ctypes_declarations.py
shapely/geometry/base.py
shapely/geos.py
shapely/impl.py
tests/test_operations.py

Closes #994
This exposes `GEOSNormalize` as a method on the geometry classes. In GEOS, this works in place, but to keep the Shapely interface consistent (other operations like simplify also return a new geometry), I made the `normalize()` method to return a new geometry (and thus first clone the geometry before normalizing it).
This seems to work for me for some simple cases. cc @tomplex @Lucidiot  
Especially given the overlay changes in GEOS 3.9.0 (where you often first need to normalize the geometry if you want to be able to compare it to an expected result across different GEOS versions), I think it would be useful to still include this in Shapely 1.8.

ENH: Add normalize() method

---

shapely/ops.py
tests/test_split.py

See #701 for background. 
I thought about using `splitter.relate_pattern(line, '...')` several times. But I'm not sure how much if any of that operation is cached, so I'm calculating one relation string and using it directly for the three checks. Fortunately the checks are all straightforward, each involving only one character.
Ping to @snorfalorpagus, just in case you would want to take a look since you have been heavily involved with the split function in the past.

ops.split: Split the line when the boundary of a splitter LineString touches the interior of the line

---

shapely/geos.py

If we have installed the `finoa`, `shapely`, `rasterio`, and package them all use Pyinstaller. 
There are multi `libgeos_c-*.so.*`, not only one. 
So, we should check the length of geos_pyinstaller_so greater and equal to 1.

fix the multi libgeos for pyinstaller

---

tests/test_wkb.py

Fixes https://github.com/Toblerity/Shapely/issues/1102.
Adds a `hostorder()` function in the test module to re-pack expected outputs in host endianness.
An alternative solution would be to manually compute the corresponding big-endian vectors, and branch on `sys.byteorder` in each test to decide which one to compare against. There are probably other reasonable alternative solutions, too.
This fix is verified on s390x, a big-endian architecture.

Fix failures in test_wkb on big-endian hosts (#1102)

---

shapely/geos.py

@sgillies I know you have said multiple times that you don't want to fix this .., but 1) it's a small change, 2) we basically do this for Linux/Mac as well (by first checking the wheel path) and 3) solves troubling import issues that can easily be avoided. 
So therefore I don't see much reason to *not* do this for Shapely 1.8 (it will still take a while until 2.0 is fully stabilized and released)
Related discussion in https://github.com/Toblerity/Shapely/pull/843#discussion_r386275247 (and also #1105, #924)

Only load conda GEOS dll if it exists (on Windows)

---

shapely/geometry/base.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/polygon.py
shapely/geos.py
shapely/linref.py

This PR refactors `super()` to be simpler, as described by [PEP 3135](https://www.python.org/dev/peps/pep-3135/) and approved in 2007 for Python 3.0.
The "old" convention (e.g. `super(C, self)`) was only required to support Python 2.

MAINT: use super() as described by PEP 3135

---

docs/code/buffer_single_side.py
docs/manual.rst

Added doc in the manual about buffer function `single_sided` option merged in #806 with doc at API level but not in the manual

Doc buffer single side

---

shapely/validation.py

Tiny PR for `shapely.validation`

Remove usage of lgeos in shapely.validation

---

_vendor/packaging/_structures.py
_vendor/packaging/markers.py
_vendor/packaging/requirements.py
_vendor/packaging/version.py
docs/manual.rst
setup.py
shapely/algorithms/polylabel.py
shapely/coords.py
shapely/geometry/base.py
shapely/geometry/polygon.py
shapely/geometry/proxy.py
shapely/geos.py
shapely/impl.py
shapely/ops.py
shapely/prepared.py
shapely/topology.py
tests/test_delegated.py
tests/test_geointerface.py

See this [Q/A](https://stackoverflow.com/questions/4015417/why-do-python-classes-inherit-object) for a background on `class Foo(object):` vs `class Foo:`.
In summary, only Python 2 required inheriting from `object`, but this is no longer necessary with Python 3 (and the docs don't use that style [here](https://docs.python.org/3/tutorial/classes.html) or [here](https://docs.python.org/3/howto/descriptor.html)). This PR keeps the base classes a bit tidier and quicker to identify.
Edits were automated using:
git ls-files -z | xargs -0 sed -i -re 's/class (.*)\(object\):/class \1:/g'
Matching files in `docs/sphinxext/*py` were ignored, as these appear to be Python2!

Python3 classes does not need to inherit from object

---

shapely/geometry/base.py
tests/test_collection.py
tests/test_multipoint.py

This deprecation in Shapely 1.8 was not yet removed in the shapely-2.0 branch

[2.0] Remove len() (__len__) for multi-part geometries

---

README.rst

We dropped Python 2.7 support for Shapely 1.8

DOC: update README to indicate Python 2.7 is not longer supported

---

docs/manual.rst

Adds the missing documentation for `shapely.ops.clip_by_rect()`

Add documentation for `shapely.ops.clip_by_rect()`

---

.github/workflows/tests.yml

According to the [Ubuntu release schedule](https://wiki.ubuntu.com/Releases), Ubuntu Xenial 16.04 is to reach it's end of standard support in a few days. Upgrading to [`ubuntu-latest`](https://github.com/actions/virtual-environments), which is currently an alias to Ubuntu Focal 20.04.

TST: ubuntu-16.04 about to reach EOL; upgrade to ubuntu-latest

---

CREDITS.txt
shapely/errors.py
shapely/wkb.py
shapely/wkt.py
tests/test_wkb.py
tests/test_wkt.py

Adds more meaningful tests for `shapely.wkt` and `shapely.wkb`. They are now covered completely.

Add tests to WKT and WKB conversion to increase coverage

---

shapely/vectorized/_vectorized.pyx
tests/test_vectorized.py

With [numpy 1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated), aliases of builtin types like `np.bool` is deprecated. This should clear up some warnings in the test suite.

MAINT: aliases of builtin types is deprecated with numpy>=1.20

---

tests/test_operations.py

The input geometry is re-ordered to have a clockwise exterior linearring i.e. is normalized.
An alternative patch is to add `.normalized()` to the result(s) of `simplify(...)`:
```diff
diff --git a/tests/test_operations.py b/tests/test_operations.py
index 23dfd08..b1d9d18 100644
--- a/tests/test_operations.py
+++ b/tests/test_operations.py
@@ -34,5 +34,5 @@ class OperationsTestCase(unittest.TestCase):
expected = loads('POLYGON ((120 120, 140 199, 160 200, 180 199, '
'220 120, 120 120))')
-        s = p.simplify(10.0, preserve_topology=False)
+        s = p.simplify(10.0, preserve_topology=False).normalize()
self.assertTrue(s.equals_exact(expected, 0.001))
```
Closes #1113

TST: fix GEOS 3.10.0dev by simplifying a normalized geometry

---

shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py

Hello,
I've just edited your library a bit. I added to method svg option to change opacity for pylygons, points, linestrings and their multiple variations.
I hope you will accept it.

ENH: Added opacity option to polygon, point, linestring and their multiple variations

---

shapely/ops.py
tests/test_voronoi_diagram.py

Replacing direct `lgeos` calls with pygeos python functions in the `shapely.ops` module.
The remaining ones to do are `polygonize`, `polygonize_full` and `nearest_points`. For `polygonize` I already have a PR in pygeos, the others still need to be added there.

Refactor shapely.ops to not use lgeos

---

_vendor/packaging/specifiers.py
docs/design.rst
shapely/geometry/base.py
shapely/ops.py
shapely/speedups/__init__.py

There are small typos in:
- _vendor/packaging/specifiers.py
- docs/design.rst
- shapely/geometry/base.py
- shapely/ops.py
- shapely/speedups/__init__.py
Fixes:
- Should read `technically` rather than `techincally`.
- Should read `preferred` rather than `prefered`.
- Should read `individual` rather than `indidivual`.
- Should read `coordinate` rather than `coodinate`.
- Should read `automatically` rather than `automaticaly`.
- Should read `access` rather than `acess`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

CHANGES.txt
shapely/geos.py

I saw some errors like `OSError: Could not find lib c or load any of its variants` in production at work. I suspect that the instances I'm using were in a very bad state, but we don't need to load libc (or its equivalent) on a *nix platform: Python has already loaded it and `free` will be found in the global symbol table.

Get free from global symbol table on Linux as we do for macos.

---

shapely/strtree.py
tests/test_strtree.py

Another follow-up on #1112. See my comment at https://github.com/Toblerity/Shapely/pull/1112#discussion_r671652931 about supporting zipped geoms/items sequence vs only supporting separate sequences. 
Assuming the zipped sequences in #1112 were a left-over from the initial version of that PR, this PR updates the STRtree constructor (and tests) to:
- only support separate sequences as `STRtree(geoms, items)`, and thus no longer supports `STRtree(zip(geoms, items))`
- also removed support for `STRtree(None)`. This didn't work before in released versions, and IMO it's cleaner to keep requiring `geoms` to be a sequence (it can still be an empty sequence)
If the intention is to mainly support the separate sequences, I would personally not support the zipped sequences (i.e. sequence tuples) to …

Only support separate geoms, items sequences in STRtree constructor

---

tests/test_strtree.py

Another follow-up on https://github.com/Toblerity/Shapely/pull/1112. Some aspects of the new `query_items` were not yet covered in the tests:
- constructing the STRtree with explicit `items` sequence + using `query_items` _without_ providing explicit items (so using a default enumeration index then)
- testing that the returned item is still correct if some geometries were dropped before constructing the GEOS tree

TST: add more tests for new query_items

---

shapely/coords.py
shapely/geometry/base.py
shapely/geometry/polygon.py
shapely/speedups/_speedups.pyx
tests/test_collection.py
tests/test_linestring.py
tests/test_multilinestring.py
tests/test_multipoint.py
tests/test_multipolygon.py
tests/test_point.py
tests/test_polygon.py

Possible fix for NumPy 1.21 DeprecationWarning for exceptions raised in `__array_interface__`.  Only `BaseGeometry.__array_interface__` still raise NotImplementedError, as it is an abstract class.
Tests for each geometry type (except GeometryCollection) are added, which creates/assigns an object array.
Comments/reviews are welcome!
Closes #1173

Silence NumPy 1.21 DeprecationWarning by raising AttributeError

---

shapely/strtree.py

This PR takes the implementation details from https://github.com/Toblerity/Shapely/pull/1064 (i.e. using  `geoms` and `idxs` sequences (lists) to store the data with which the GEOSSTRtree gets created, instead of using a mapping), but cleanly on top of the new interface (`query_geoms`/`query_items`) from https://github.com/Toblerity/Shapely/pull/1112, without all the discussion on the interface from #1064.
It doesn't change any user facing API now after #1112, but only refactors the implementation (how to store the items). As mentioned in https://github.com/Toblerity/Shapely/pull/1112#issuecomment-875108728, this version is closer to what we would do in the shapely-2.0 branch on top of the C-based STRtree (which I started in https://github.com/Toblerity/Shapely/pull/1161). IMO it is …

Refactor STRtree implementation to store geoms/idx sequences instead of reverse mapping

---

shapely/strtree.py
tests/test_strtree.py

As a follow-up on https://github.com/Toblerity/Shapely/pull/1112, if we don't have concrete plans to change the API, we shouldn't raising a warning in the constructor every time?

Remove the DeprecationWarning from STRtree constructor

---

CHANGES.txt
shapely/_buildcfg.py
shapely/geos.py
tests/test_dlls.py

I added the directory /opt/homebrew/lib to the list of directories to be searched for the GEOS
shared library. Homebrew installs into /opt/homebrew rather than /usr/local on systems with the new Apple Silicon (M1) chip.
Actual behaviour of
`python -c "from shapely.geos import lgeos"`
is
```
File "<string>", line 1, in <module>
File "/Users/cuntz/.pyenv/versions/3.9.6/envs/test-cartopy/lib/python3.9/site-packages/shapely/geos.py", line 136, in <module>
_lgeos = load_dll('geos_c', fallbacks=alt_paths)
File "/Users/cuntz/.pyenv/versions/3.9.6/envs/test-cartopy/lib/python3.9/site-packages/shapely/geos.py", line 60, in load_dll
raise OSError(
OSError: Could not find lib geos_c or load any of its variants …
```

Added /opt/homebrew/lib for GEOS shared library

---

CHANGES.txt
docs/conf.py
docs/index.rst
docs/manual.rst
docs/migration.rst

In preparation of a next (final?) Shapely 1.8 release, I wrote up a more detailed page on the warnings included in Shapely 1.8 (and upcoming changes in 2.0), and how to update your code to get rid of the warnings / prepare it for Shapely 2.0.

Add migration guide with explanation how to update your code for Shapely 1.8 / 2.0

---

shapely/geometry/polygon.py
tests/test_pickle.py

xref https://github.com/Toblerity/Shapely/issues/988
Together with https://github.com/Toblerity/Shapely/pull/1161, this is the last remaining usage of lgeos / ctypes in the shapely-2.0 branch.

Refactor pickling of LinearRing to not use lgeos

---

CHANGES.txt
docs/migration.rst
shapely/geometry/base.py
shapely/geometry/proxy.py
tests/test_geometry_base.py

See https://github.com/Toblerity/Shapely/pull/1181 (and https://github.com/Toblerity/Shapely/pull/1180/files#r693378882). _If_ we want to disallow it for Shapely 2.0, this is adding a deprecation warning for it for 1.8

Deprecate setting of custom attributes on geometry objects

---

tests/test_polygon.py

GEOS changed to actually allow this, so PyGEOS now checks for this itself (giving a ValueError instead of GEOSException). Leaving the GEOSException for now in the pytest.raises as well, for if you are using this with released pygeos.
See https://github.com/pygeos/pygeos/pull/378

TST: creating linearring with too few coordinates gives different error with latest GEOS

---

shapely/geometry/base.py
shapely/geometry/collection.py
shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py
tests/test_geometry_base.py

xref https://github.com/Toblerity/Shapely/pull/1180/files#r693378882
PyGEOS geometries are "immutable", not only regarding the coordinates of the geometry, but also the python object: you can't assign random attributes as you can do with a normal class defined in python (this is because they are C extension types):
```python
>>> import pygeos
>>> p = pygeos.Geometry("POINT(1 1)")
>>> p
<pygeos.Geometry POINT (1 1)>
>>> p.name = "test"
...
AttributeError: 'pygeos.lib.Geometry' object has no attribute 'name'
```
However, because in Shapely we still create a Python-defined subclass for each of the geometry types (and register this, so the C code will actually instantiate those subclasses), we get the typical behaviour of standard python classes still being "mutable" objects:
```python
>>> p …
```

[2.0] Disallow setting custom attributes on geometry objects

---

shapely/strtree.py
tests/test_strtree.py

This is for the shapely-2.0 branch, to do the equivalent of https://github.com/Toblerity/Shapely/pull/1112 or https://github.com/Toblerity/Shapely/pull/1064 (and ideally only gets done when one of those PRs is merged).
This shows how the `lib.STRtree` (the C object) will just contain primary keys, which are mapped to geometries (or other items) in the `query` method using the returned indices.

Refactor strtree to not use lgeos / ctypes

---

shapely/geometry/geo.py
tests/test_geointerface.py

Closes #1179
Note that LinearRing type geometry is not actually supported in the GeoJSON spec, and the `__geo_interface__` spec doesn't explicitly mention it (https://gist.github.com/sgillies/2217756). 
But since we create python dicts with "LinearRing" type in `mapping(linearring)` or `linearring.__geo_interface__`, it seems most logical to indeed support the roundtrip in `shape(..)` as well.

Support LinearRing objects in the shape() function

---

shapely/geos.py

The Debian package build for 1.8rc1 failed due to not finding geos_c:
```
FileNotFoundError: [Errno 2] No such file or directory: b'liblibgeos_c.a'
```
This is fixed by [reverting the `load_dll` change from `geos_c` to `libgeos_c` on Linux](https://github.com/Toblerity/Shapely/commit/611a0b3b2047bf8a49db32dc4b30684a10f5b6eb#diff-449c80fbb0cac229a562aa3662da054b7ccdd3533e46d7e66cdf623fba6dd507).

Fix loading geos_c library on Linux.

---

appveyor.yml
requirements-dev.txt

[Attempts](https://github.com/shapely/shapely-wheels/pull/10/commits/d8700bbee937d515a197353452b0651783abc23c) to build Shapely for Python 3.10 on Windows [flopped with an error](https://ci.appveyor.com/project/frsci/shapely-wheels/builds/41413927/job/q8r6r6w36ae35527#L2172):
> _speedups.obj : error LNK2001: unresolved external symbol _PyGen_Send
which is described at https://github.com/cython/cython/issues/3876
This was resolved as of cython version 0.29.22, but this PR uses the latest cython update in the 0.29.x series.
Xref #1215 and https://github.com/shapely/shapely-wheels/pull/10

Upgrade cython==0.29.24 to work with Python 3.10

---

.github/workflows/tests.yml
appveyor.yml
shapely/algorithms/polylabel.py
shapely/geometry/base.py

Another maintenance update for shapely-1.8, to use the latest versions of GEOS.
- GEOS 3.9.2 [announcement](https://lists.osgeo.org/pipermail/geos-devel/2021-November/010526.html)
- GEOS 3.10.1 [announcement](https://lists.osgeo.org/pipermail/geos-devel/2021-November/010556.html)
If we get around to shapely-1.8.1, the binary wheels should probably be packaged with GEOS 3.9.2.

CI: Upgrade GEOS versions

---

tests/test_singularity.py

Xref https://github.com/pygeos/pygeos/issues/213 and https://github.com/pygeos/pygeos/pull/431
This test was restored to it's previous state.

TST: linearring closing logic was changed with pygeos

---

shapely/geometry/base.py

Same as https://github.com/Toblerity/Shapely/pull/1214 but based on the right branch.
Just for your information `geoviews` was using this property in a couple of internal utils and in its test suite.

Fix the array_interface_base property

---

shapely/_geometry_helpers.pyx
shapely/_pygeos_api.pxd
src/c_api.h
src/coords.c
src/geos.c
src/lib.c
src/pygeom.c
src/strtree.c
src/ufuncs.c
src/vector.c

I missed one aspect in https://github.com/Toblerity/Shapely/pull/1237 to get a basic working package (due to testing it in an environment in which I still had pygeos installed, so the cython code was picking up the pygeos package instead ..).
I didn't yet do a full rename of all PyGEOS_.. functions.
cc @caspervdw

Minimal pygeos->shapely renaming in C code to get cython API working

---

shapely/tests/test_creation.py

Small error in my pygeos -> shapely renaming which caused some test failures

TST: fix search/replace mistake in test_empty

---

shapely/geometry/base.py
shapely/geometry/polygon.py

On top of #1237, so only the last commit is relevant.
The tests for hash-ability were still failing, for two reasons:
- There was still a `__hash__ = None` in the code, effectively making a class unhashable
- We defined a `__eq__` in the python-level BaseGeometry class, and when you subclass, you need to implement neither or both of `__eq__` and `__hash__` (see https://docs.python.org/3/reference/datamodel.html#object.__hash__)
- I now removed the `__eq__` in the python layer, keeping the `GeometryObject_richcompare` in the C extension type in `pygeos.c` (but in principle we could also do it the other way around I think)

BUG: fixup the hash-ability of geometries

---

shapely/geometry/polygon.py
tests/test_hash.py

Supersedes #985
The hash implementation is better than the previous one that existed in shapely several versions ago, as it is now based on WKB.
Now geometries can be used as dict keys to do things like this:
```
>>> from shapely.geometry import Point
>>> d = {}
>>> d[Point(1, 2)] = "X"
>>> d[Point(1.0, 2.0)]
'X'
```

BUG/TST: fix hashing for Polygon + update tests

---

.github/workflows/release.yml
.gitignore
MANIFEST.in
MANIFEST_pygeos.in

A few edits to `MANIFEST.in` were necessary to get `python -m build` to work as expected.
This should probably be integrated into the CI at some point.

Update MANIFEST.in to enable 'python -m build` to work

---

MANIFEST.in

This is similar to #1249 and somewhat fixes #1263 for shapely-1.8
It seems that cythonized C files were packaged in the source distribution, which is not what we want to have.

Update MANIFEST.in to exclude *.c files

---

docs/manual.rst

Found a typo in the docs that listed the version as 1.7.0.

Update manual version from 1.7.0 to 1.8.0

---

shapely/tests/geometry/test_geometry_base.py

Closes https://github.com/shapely/shapely/issues/1056
This was already implicitly fixed by https://github.com/shapely/shapely/pull/1239 by removing the python `__eq__` implementation and only keeping the C-level implementation (which already correctly returned NotImplemented when needed). But this PR is still adding an explicit test for it.

TST: test that Geometry subclasses properly return NotImplemented in comparison with non-geometry

---

shapely/geometry/polygon.py
shapely/tests/geometry/test_polygon.py

Constructing a Polygon from a LineString worked before, but no longer on the main branch (noticed this while testing out shapely 2.0 with geopandas). This PR restores that behaviour.
For example with shapely 1.8:
```
In [3]: import shapely
In [4]: import shapely.geometry
In [5]: shapely.geometry.box(0,0,1,1)
Out[5]: <shapely.geometry.polygon.Polygon at 0x7f4ce490cfd0>
In [6]: shapely.geometry.box(0,0,1,1).boundary
Out[6]: <shapely.geometry.linestring.LineString at 0x7f4d36342d90>
In [7]: shapely.geometry.LinearRing(shapely.geometry.box(0,0,1,1).boundary)
Out[7]: <shapely.geometry.polygon.LinearRing at 0x7f4ce4868f10>
In [8]: shapely.geometry.Polygon(shapely.geometry.box(0,0,1,1).boundary)
Out[8]: <shapely.geometry.polygon.Polygon at 0x7f4ce4868490>
In [9]: shapely.__version__
Out[9]: …
```

BUG: fix Polygon() constructor from a LineString

---

shapely/tests/geometry/test_collection.py
shapely/tests/geometry/test_emptiness.py
shapely/tests/geometry/test_linestring.py
shapely/tests/geometry/test_multilinestring.py
shapely/tests/geometry/test_multipoint.py
shapely/tests/geometry/test_multipolygon.py
shapely/tests/geometry/test_point.py
shapely/tests/geometry/test_polygon.py

Since the geometry objects are now no longer sequence-like objects / objects with an array interface, those objects should now interoperate fine with numpy arrays, and the warning should be no longer be raised.

TST: remove filterwarnings for numpy 1.21

---

src/ufuncs.c

Instead of going through `GEOSEnvelope` and getting the coordinates of that rectangular geometry object. This is simpler code, and quite a bit faster (it avoids the construction/destruction of the polygon object).
See https://github.com/libgeos/geos/pull/554 for context

PERF: speed-up bounds function with GEOSGeom_getXMin et al (GEOS >= 3.7.0)

---

shapely/errors.py
shapely/wkb.py
tests/test_geos_err_handler.py
tests/test_predicates.py
tests/test_wkb.py

Related to the discussion in https://github.com/shapely/shapely/issues/991
This removes some custom exception subclasses that are no longer used after the merge with pygeos (eg reading invalid WKB or WKT now raises a GEOSException)

CLN: remove no longer used custom error classes

---

shapely/errors.py
src/geos.c

See https://github.com/shapely/shapely/pull/1306#issuecomment-1032362619, and related to discussion in https://github.com/shapely/shapely/issues/991

REF: Move ShapelyError base class to C, GEOSException becomes subclass

---

shapely/__init__.py
shapely/decorators.py
shapely/errors.py
shapely/set_operations.py
shapely/tests/test_misc.py
shapely/tests/test_set_operations.py
shapely/tests/test_strtree.py

We had two classes as a left-over from the merger. I removed the top-level one (from pygeos) and used the one in the `shapely.errors` submodule.

Consolidate error class for unsupported GEOS version functionality

---

.github/workflows/tests.yml

Upgrade GEOS used in the CI for the `maint-1.8` maintenance branch to [3.10.2 released 2022-01-15](https://lists.osgeo.org/pipermail/geos-devel/2022-January/010638.html)

maint-1.8 CI: upgrade GEOS 3.10.1 (2021-11-02) to 3.10.2 (2022-01-15)

---

shapely/tests/geometry/test_linestring.py
shapely/tests/test_io.py
tests/test_create_inconsistent_dimensionality.py

Numpy 1.22 starts to check the dtype of an array before the dimensionality, and so when passing a 1D object array into a ufunc that expects a 2+D array, we now get a TypeError instead of a ValueError (and this 1D object array comes from passing an inconsistent dimensioned list of coordinates).
We have numpy 1.22 on the build with GEOS main, but the failures were not visible because that build allows failures .. (there are more failures related to GEOS that would need to be fixed first)

TST: update tests to pass with numpy 1.22 and pytest 8

---

shapely/errors.py

And made it stop subclassing TypeError and ValueError, as the deprecation message said.

Remove deprecation warning from GeometryTypeError

---

.travis.yml

Given that we have only limited "credits" for Travis, we can best limit the number of builds, and for example not build on _every_ commit in a PR.
Using the conditions from https://docs.travis-ci.com/user/conditions-v1
Will additionally check if we can still run it when we edit eg the build configuration (as we detect with github actions)

CI: only build Travis on the main branch (not PRs)

---

shapely/geometry/base.py
shapely/tests/geometry/test_geometry_base.py

Part of https://github.com/shapely/shapely/issues/975. This PR already deprecates the `GeometryType()` method, which isn't used internally or used in the documentation.

DEPR: deprecate the GeometryType attribute

---

.github/workflows/tests.yml
pyproject.toml
setup.py

Tests are failing on the main branch. It might be that setuptools broke something (that's the only thing that I notice that is different with the passing build of 4 days ago, a version update of setuptools of 62.1 -> 62.2), although I don't directly see anything mentioned in their changelog that would explain this (https://setuptools.pypa.io/en/latest/history.html#v62-2-0). It seems that it no longer ignores the packages listed in pyproject.toml, even when directly calling `python setup.py build_ext`.

CI: fix tests with latest setuptools

---

docs/conf.py
docs/constructive.rst
docs/coordinates.rst
docs/creation.rst
docs/geometry.rst
docs/io.rst
docs/linear.rst
docs/measurement.rst
docs/predicates.rst
docs/set_operations.rst
docs/strtree.rst
docs/testing.rst

This already allows to build the docs and all those autodoc reference pages (I still get a bunch of warnings to resolve though).

DOC: replace pygeos -> shapely in the reference docs

---

shapely/geometry/collection.py
shapely/geometry/geo.py
shapely/geometry/linestring.py
shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py
shapely/geometry/multipolygon.py
shapely/geometry/point.py
shapely/geometry/polygon.py

This makes a few changes to the main docstrings of the Geometry subclass objects:
- "Example" -> "Examples" to follow numpydoc convention
- Combined the class docstring with the `__new__` docstring. I think this is more useful for users (interactively, you will typically only check the class docstring (`Polygon?` in IPython)).
- Some small formatting changes, and ensuring everything builds fine with sphinx.

DOC: update class (init/new) docstrings of Geometry subclasses

---

.readthedocs.yml
docs/conf.py
docs/environment.yml
environment.yml
readthedocs.yml

Trying to get the readthedocs build working again. I activated this branch, and so the build output can be seen here (it is now "passing"): https://readthedocs.org/projects/shapely/builds/16978294/
The actual doc build is still failing, because the plot directives are still erroring.
I also switched to use mamba instead of conda, which speeds up the env install step from 4 to 2 min.

DOC: fix / consolidate the readthedocs configuration

---

shapely/geometry/base.py
tests/test_linear_referencing.py
tests/test_operations.py

One possible solution for part of https://github.com/shapely/shapely/issues/1276

Add aliases for project/interpolate/representative_point methods

---

shapely/constructive.py

xref https://github.com/shapely/shapely/issues/1276
The Geometry class' `simplify()` method has a default of `preserve_topology=True`, while the vectorized function from pygeos was using `True`. But I think we have been thinking in the past we should probably move to `True` anyway (to return valid geometries by default, eg https://github.com/pygeos/pygeos/issues/233#issuecomment-943856854), and that also ensures that the function and geometry class method use a consistent default.

Change simplify() preserve_topology default to True (match the Geometry method)

---

asv.conf.json
benchmarks/benchmarks.py

This fixes the benchmark suite as part of the PyGEOS to Shapely 2.0 migration.  Other than minor whitespace changes, the only changes here are instructions at the top of `benchmarks.py` and find / replace `pygeos` => `shapely`.
Note: `STRtree` benchmarks are currently broken pending #1422 (they were written for the indices-only tree API).  The other benchmarks work properly.

TST: Update benchmarks for pygeos=>shapely

---

shapely/geometry/base.py
shapely/geometry/collection.py
shapely/tests/geometry/test_collection.py

Closes https://github.com/shapely/shapely/issues/956
Currently a GeometryCollection that consists of multiple empty geometries (which is considered as an empty geometry), does not return those geometries in the `.geoms` attribute (because of a special casing in our code for this, to specifically return an empty list).
Actually returning the empty subgeoms makes this more correct (the actual GEOS geometry has those empty subgeoms, also the WKT now displays them) and consistent with the top-level functions `get_num_geometries` / `get_geometry` (to index into the sub-geoms).

API: all-empty GeometryCollection .geoms to return empty subgeoms

---

shapely/geometry/base.py
shapely/geometry/polygon.py
shapely/tests/test_creation.py
shapely/tests/test_geometry.py
shapely/tests/test_io.py
src/pygeom.c

Closes https://github.com/shapely/shapely/issues/999. This removes the `__geom__` dunder attribute and keeps `_geom` (renaming the `_ptr` inherited from pygeos to `_geom`).

API: remove __geom__, keep _geom read-only access to GEOS pointer

---

README.rst
docs/installation.rst

This updates / consolidates the documentation on installing shapely. Apart from some pygeos->shapely renaming, I did:
* I moved most content about installation in the README to the specific documentation page (and linking that page), and in the README kept it short. My goal here is to avoid duplication (and going into details in the README). 
* I tried to combine the installation doc page from pygeos with some of the content from Shapely's README. But I didn't keep everything (some aspects were a bit outdated), so it would be good to give this a check.

DOC: update the installation documentation

---

.github/workflows/tests.yml

GEOS 3.11 was recently [released](https://lists.osgeo.org/pipermail/geos-devel/2022-July/010728.html), so adding it to the CI matrix.
According to [PEP 664](https://peps.python.org/pep-0664/), Python 3.11 will be released October 2022, so this "2022" matrix item should be updated when supported by GHA.

CI: add testing for 2022, including GEOS-3.11

---

.github/workflows/tests.yml
tests/test_parallel_offset.py

Similar to #1437 but for the maintenance branch for shapely 1.8

CI: add testing for 2022, including GEOS-3.11 (maint-1.8)

---

.github/workflows/release.yml
.github/workflows/tests.yml
README.rst
setup.py

For Shapely 2.0, it time to finally drop Python 3.6. NumPy 1.14+ is required for Python 3.7+ support.
As well removing an old version of Python, this will enable #1426 to move static metadata to `pyproject.toml`.
Closes #1205

Require Python 3.7+, NumPy 1.14+

---

.github/workflows/release.yml

Shown in recent builds:
> The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583

CI: macOS-10.15 is deprecated, upgrade to macOS-11

---

shapely/geometry/base.py
shapely/geometry/geo.py
tests/__init__.py
tests/conftest.py
tests/test_affinity.py
tests/test_ndarrays.py

This cleans up some logic that was used when numpy was optional. As of shapely-2.0 it is required.

MAINT: remove workarounds when numpy was optional

---

.github/workflows/release.yml

CI: macOS-10.15 is deprecated, upgrade to macOS-11 (maint-1.8)

---

shapely/geometry/base.py
shapely/geometry/polygon.py

This was partially discussed in #983 to rename a few variables. But also clean-up variables that are no longer used with shapely-2.
- Rename `__p__`→`_parent` to make it "private", and generally [avoid non-standard dunder names](https://dbader.org/blog/meaning-of-underscores-in-python). Another consideration is to rename it to `__parent` to enable name mangling for sub classes, see docs [Private Variable](https://docs.python.org/3/tutorial/classes.html#private-variables) and [Reserved classes of identifiers](https://docs.python.org/3/reference/lexical_analysis.html#reserved-classes-of-identifiers). Another consideration is with [`__del__`](https://docs.python.org/3/reference/datamodel.html#object.__del__), "Python guarantees that globals whose name begins with a single underscore are …

CLN: Rename `__p__`→`_parent`, clean-up `gtag`, `_factory` and `__rings__`

---

shapely/geometry/base.py
shapely/tests/geometry/test_geometry_base.py

The fixed precision overlay operation (part of OverlayNG from GEOS) is a new feature in 2.0, and this is already available in the new top-level functions, but it would be good to expose this on the existing methods as well. This is adding the `grid_size` keyword and passing this through.

ENH: expose fixed precision overlay (grid_size keyword) in the Geometry methods as well

---

shapely/ctypes_declarations.py

This seems to fix a segmentation fault when calling this function in the test suite on aarch64-darwin. Fixes #1473.

Fix GEOSMinimumClearance signature.

---

shapely/tests/geometry/test_geometry_base.py
shapely/tests/test_creation.py
src/pygeom.c

Closes #1330
In https://github.com/shapely/shapely/pull/1414 we already removed all usage of the base class Geometry() constructor in code, tests and documentation. But the constructor itself wasn't yet removed, so it could still be called. This PR also actually makes the base class not callable.

CLN: actually remove the base class Geometry() constructor

---

shapely/affinity.py
shapely/geometry/base.py
shapely/geometry/geo.py
shapely/ops.py
shapely/tests/geometry/test_collection.py
shapely/tests/geometry/test_geometry_base.py
tests/test_linemerge.py
tests/test_make_valid.py
tests/test_pickle.py
tests/test_split.py
tests/test_svg.py
tests/test_voronoi_diagram.py

This PR deprecates the `.type` attribute, which is an alias for `.geom_type`. It is expected this attribute is used externally with lots of other projects, so this may cause a bit of noise. Are we sure we want to deprecate it?
Closes #975

DEPR: deprecate the type attribute

---

docs/manual.rst
shapely/geometry/linestring.py
tests/test_parallel_offset.py

See https://github.com/shapely/shapely/issues/1276
ref foss4g2022 codesprint
parallel_offset as ALIAS OF offset_curve new method

Make parallel_offset an alias for offset_curve

---

shapely/geometry/base.py
shapely/geometry/linestring.py
tests/test_buffer.py
tests/test_parallel_offset.py

Fixes #1483 and fixes #1515 for the shapely 1.8.x maintenance branch.
I'll apply a similar approach for the main branch soon (sometime after #1514 is merged).

Raise ValueError for non-finite distance to buffer/parallel_offset (maint-1.8)

---

docs/migration.rst

Distutils is deprecated, so the documentation should suggest an alternative method to compare versions (one of [many](https://stackoverflow.com/q/11887762)).
Also, this approach needed `version.parse("2.0a1")` to be compared to work with the existing pre-release.

DOC: update migration guide to use 'packaging' instead of 'distutils'

---

src/coords.c
src/geos.c
src/geos.h

Similar as https://github.com/pygeos/pygeos/pull/436, but now for getting coordinates.
Small example showing the speed-up (10,000 polygons of 100 vertices):
```python
geoms = shapely.polygons(np.random.randn(10000, 100, 2))
In [10]: %timeit shapely.get_coordinates(l)
13.6 ms ± 314 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)   # <-- main
6.46 ms ± 322 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)   # <-- PR
```

PERF: use GEOSCoordSeq_copyToBuffer for get_coordinates (GEOS >= 3.10)

---

CHANGES.txt
docs/release.rst
docs/release/1.x.rst

This implements the suggestion from https://github.com/shapely/shapely/pull/1442#issuecomment-1223326351, following up on the changelog PR:
- Include the content of CHANGES.txt verbatim into the docs (`docs/release/1.x.rst`), instead of using the include directive
- Remove the old releases (before 1.8) from CHANGEST.txt, and refer to the docs instead (this keeps that file shorter, plus reduces the duplication from the previous point)
- Include the changes from recent 1.8.x releases that were currently only present on the maint-1.8 branch
- For 2.0, only add a summary to CHANGES.txt, referring to the docs for the full changelog. This way, we can at least include the dates of the releases, and also include the changes in consecutive alpha/beta/rc releases that are not relevant for the final …

DOC/RLS: update CHANGES.txt with last releases, move old releases to docs

---

shapely/errors.py

I didn't really think about the backwards compatibility story when cleaning up those exception subclasses we no longer use ourselves (-> https://github.com/shapely/shapely/pull/1306), but since we didn't explicitly deprecate those, we can actually still do that now in 2.0
Triggered by seeing `pycsw` importing one of those errors: https://github.com/geopython/pycsw/blob/de3278523af546b3cdf5dc5a23cc5d61b4efab8e/pycsw/core/repository.py#L40-L43

COMPAT: keep old exception sublcasses as (deprecated) ShapelyError aliases

---

shapely/_geometry_helpers.pyx
shapely/geometry/base.py

For context, see https://github.com/SciTools/cartopy/issues/2076#issuecomment-1243294605. Cartopy is using `geom_factory` in their cython code to create a shapely geometry from a GEOS geometry object pointer they create in cython. This PR adds back a (deprecated) `geom_factory` function that did this before in <=1.8. 
Of course this is not really safe to use (it requires that you are using the exact same GEOS version and build), but this caveat already applies to cartopy+shapely now as well, so this just keeps that situation a bit longer. Longer term, cartopy will ideally stop passing pointers to shapely, for example by using shapely more instead of interfacing directly with GEOS (cfr https://github.com/SciTools/cartopy/issues/805)
Also related to …

COMPAT: keep (deprecated) geom_factory for downstream packages (cartopy)

---

shapely/set_operations.py
shapely/tests/test_set_operations.py

xref https://github.com/shapely/shapely/issues/1276
Since we already have `unary_union`, and this is also used in GeoPandas (and PostGIS also uses this), we thought it best to keep that name. But also keeping `union_all` because this is consistent with `intersection_all` etc (and we don't want to rename the `_all` functions to `unary_`, since that is also not a super clear name if you are not familiar with it)

Add unary_union alias for top-level union_all

---

.readthedocs.yml
docs/conf.py

After https://github.com/shapely/shapely/pull/1529, the doc build on readthedocs was failing for latex (pdf). Although if this rendering can't be done for pdf, then I am not sure that the approach of https://github.com/shapely/shapely/pull/1529 will actually result in proper pdf docs .. (I am also not sure how important this is)

DOC/CI: fix doc build for latex + re-enable epub and htmlzip

---

benchmarks/benchmarks.py
shapely/geometry/point.py

This avoids creating a separate array for the x and y argument, and then stacking both arrays (this is what happens in the `points(..)` under the hood, as that can both accept a single 2D array of separate x/y arrays):
```
In [2]: %timeit Point(1, 1)
12.6 µs ± 442 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)    # <-- main
4.34 µs ± 60.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)   # <-- PR
```

PERF: improve performance of Point(x, y) constructor

---

shapely/geometry/base.py
shapely/tests/geometry/test_geometry_base.py

For context, see https://github.com/SciTools/cartopy/issues/2076#issuecomment-1243294605. 
While trying to make cartopy run with Shapely 2.0, I discovered that they relied on geometry objects being weakref-able. And in Shapely 2.0 we broke that (first by making it an extension type in C (in pygeos), and then afterwards by adding `__slots__` to the python subclasses, https://github.com/shapely/shapely/pull/1181)
This PR makes the geometry objects again weakref-able. 
There is the question whether we want to do this, with the main tradeoff being that this adds 8 bytes of memory to each geometry object (although, given that each coordinate is also 8 bytes, this is only somewhat significant for Point objects)

Make Geometry objects weakref-able

---

.github/workflows/lint.yml
CITATION.cff
CITATION.txt

This PR adds a [CITATION.cff](https://citation-file-format.github.io/) file, to replace CITATION.txt. As documented elsewhere, this file is used by a variety of sources, including GitHub, Zenodo, and others. It can be converted into other citation formats, like bibTeX.
The file is intended to be used to cite the software (not the manual), and should ideally be updated before each release to update "version" and "date-released" fields. (If there were a HOW-TO-RELEASE document, then I'd add this note.)
It does not require any integration with Zenodo, but if it were enabled (@sgillies would need to do this for #1379) then a DOI would be issued for each release or tag pushed from GitHub. (There is already a placeholder in README.rst left over from PyGEOS to show the latest DOI). I've …

Add CITATION.cff, remove CITATION.txt

---

.travis.yml

The linux aarch64 wheels were not yet uploaded for the previous alpha (see https://github.com/shapely/shapely/issues/962#issuecomment-1203723128), because the PyPI authentication wasn't yet set up in travis.yml
However I ran into the issue that the token is "too large" for travis to encrypt (apparently something for older repos ..), see https://travis-ci.community/t/travis-encrypt-data-too-large-for-pypi-tokens-with-older-repos/5792/10 or https://github.com/travis-ci/travis.rb/issues/687 for context.
I followed a workaround mentioned in those threads (and similarly as done in eg https://github.com/rafguns/linkpred/commit/f0a4ebdfa4532f519e5e5c74d17b98d12e58cdc3) to split the secret. No idea if I did it correctly, I suppose we will only see with the next time we try to upload .. 
Basically …

CI: add PyPI token for travis wheel uploads (splitted secret)

---

CHANGES.txt
shapely/set_operations.py
shapely/tests/test_set_operations.py

Targeted fix for https://github.com/shapely/shapely/issues/1332, in case this might be merged quicker for a beta release than a more general solution for all reducers (https://github.com/shapely/shapely/pull/1501, https://github.com/shapely/shapely/pull/1540). unary_union is the only one that already existed in 1.8, and so the only one that people might run into when upgrading from 1.8->2.0 (as people already reported in https://github.com/shapely/shapely/issues/1332 and https://github.com/shapely/shapely/issues/1545)
@brendan-ward I basically extracted those parts from your PR that related to unary_union.

API: restore unary_union behaviour on empty list to return empty GeometryCollection

---

.github/workflows/tests.yml

Enables the Python 3.11 job, and updates the used checkout, setup-python and cache actions to their latest versions.

CI: Enable Python 3.11, update used actions

---

.github/workflows/release.yml

Update the used actions in the release CI to their latest version.
The main improvement is on the [cibuildwheel](https://github.com/pypa/cibuildwheel) side, which include Python 3.11 support, better Apple Silicon support and many bugfixes. It also expands the API, see [their changelog](https://cibuildwheel.readthedocs.io/en/stable/changelog/) for details.

release CI: Update used actions to latest versions / Python 3.11 wheels

---

docs/migration_pygeos.rst
shapely/set_operations.py
shapely/tests/test_set_operations.py
src/ufuncs.c

Next iteration on https://github.com/shapely/shapely/pull/1540 and https://github.com/shapely/shapely/pull/1501 
Addresses https://github.com/shapely/shapely/issues/1332
See https://github.com/shapely/shapely/pull/1540#discussion_r990693467 for details. This PR implements `intersection_all` and `symmetric_difference_all` as a generalized ufunc with the last dimension of the array that gets reduced. This way we can implement the reducing set operations without relying on the `.reduce` mode of standard ufuncs. 
To achieve the same functionality from before, we only have to reshape the input array to move the axis to be reduced (based on the `axis` keyword) to the last dimension.
I still need to add some more tests for the cases brought up in the various issues and PRs (and copy from …

Refactor reducing set operations as gufuncs + return emtpy collection for empty/all-None input

---

pyproject.toml
setup.py

It seems that maint-1.8's PEP 517/518 was incomplete, as a build-backend was not specified. <s>Also, unpin setuptools version, as newer versions should work too.</s> A "wheel" requirement was not added, as this should automatically be included.
Closes #1568

Specify build-backend for PEP 517/518

---

tests/test_doctests.py
tests/test_hash.py

Two files (`tests/test_doctests.py` and `tests/test_hash.py`) are refactored from older testing paradigms into pytests to resolve a few warnings from tests that returned non-None objects.
```
=============================== warnings summary ===============================
tests/test_doctests.py::test_suite
$PREFIX/lib/pypy3.8/site-packages/_pytest/python.py:201: PytestReturnNotNoneWarning: Expected None, but tests/test_doctests.py::test_suite returned <unittest.suite.TestSuite tests=[<doctest._DocTestSuite tests=[$SRC_DIR/tests/test_binascii_hex.txt]>]>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
f"Expected None, but {pyfuncitem.nodeid} returned {result!r}, which will be an error in a "
tests/test_hash.py::test_point …
```

Resolve pytest warnings (maint-1.8)

---

shapely/geometry/base.py
shapely/geometry/linestring.py
tests/test_buffer.py
tests/test_parallel_offset.py

Similar to #1516 for `maint-1.8`, raise ValueError for non-finite distance values passed to buffer or offset_curve (aka parallel_offset) functions.
Previous behavior for shapely-2.0 did not crash (as it did for 1.8), but would be inconsistent:
- distance float('inf') would raise "GEOSException: IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers"
- distance float("nan") would not raise or warn, but would return None

Raise ValueError for non-finite distance to buffer/offset_curve

---

.github/workflows/tests.yml
shapely/geometry/base.py
shapely/tests/geometry/test_geometry_base.py
src/pygeom.c
src/pygeom.h

Closes https://github.com/shapely/shapely/issues/1575
I haven't yet checked if this actually fixes it on PyPy, but it's a potential fix for the issue. My understanding is that on PyPy also extension types defined in C support weakref by default, so therefore adding this manually in the subclasses as we did here is failing (https://foss.heptapod.net/pypy/pypy/-/issues/2670#note_45293)
The implementation of adding a  `weakreflist` slot is mimicked from numpy (how they do that for the ndarray extension type)

BUG: move weakref-able implementation to base C extension type (fix PyPy)

---

docs/migration_pygeos.rst
shapely/constructive.py

See https://github.com/shapely/shapely/issues/1276#issuecomment-1295427157 for context

API: rename 'radius' -> 'distance' keyword in shapely.buffer() for consistency

---

shapely/geometry/point.py
shapely/tests/geometry/test_point.py

Closes https://github.com/shapely/shapely/issues/1587

Allow passing len-1 array for x and y coordinates in Point(..) (compat with 1.8)

---

.github/workflows/tests.yml

Because we limit the doctests to a single python/GEOS version combo, we need to remember updating the check if the python or GEOS version gets updated.

CI: ensure doctests are running

---

requirements-dev.txt

It is no longer needed since the `shapely.plotting` module was added in cbf28cc.
Fixes #1145.

MAINT: Remove descartes from requirements-dev.txt

---

docs/release/2.x.rst
shapely/tests/geometry/test_point.py

See https://github.com/shapely/shapely/pull/1590#issuecomment-1295823911 for context
With shapely 1.8:
```
In [1]: from shapely.geometry import Point
In [2]: Point([(1, 2), (3, 4), (5, 6)]).wkt
Out[2]: 'POINT (1 2)'
```
One 2.x, this raises an error instead of ignoring the other coordinates. This PR adds an explicit test for this and a note in the release notes.

Document Point(..) constructor change no longer allowing coordinate sequence of len > 1

---

.github/workflows/release.yml
.github/workflows/tests.yml
.travis.yml
pyproject.toml
tests/test_locale.py

Add a Python 3.11 classifier.
This follows on from #1596 to test Python 3.11 for the "dev" builds (although presumably 3.12-dev could be considered), and also bump NumPy to 1.23.4.

MAINT: Add Python 3.11 classifier and upgrade to GEOS 3.11.1; other CI upgrades

---

docs/installation.rst
pyproject.toml
requirements-dev.txt

This PR has a few related aims:
- Remove requirements-dev.txt
- Expand the optional dependencies (in pyproject.toml) for "test" and "docs"

MAINT: remove requirements-dev.txt; expand optional dependencies in pyproject.toml

---

shapely/geometry/base.py
shapely/ops.py

This PR attends to a TODO to deprecate `resolution` from `buffer()`.
Also a few clean-ups, updating docstrings, using Sphinx directives, etc.

DOC: clean-up docstrings and Sphinx markup for deprecated functions

---

shapely/_geometry.py

This cleans up a deprecation from PyGEOS, that should not apply to shapely 2.0

DEP: remove 'preserve_topology' from 'set_precision()'

---

docs/manual.rst
shapely/geometry/base.py
tests/test_equality.py

Xref to #889 and 26cafd027ab26a6b728ce8a3d26f0b9c8b114bf1
This function was deprecated for 1.8 and planned to be removed for 2.0. But willing to hold off for another release if there is any compelling reason.
---
On a related topic, these signatures have different `tolerance` defaults:
- [`shapely.geometry.base.BaseGeometry.equals_exact(self, other, tolerance)`](https://github.com/shapely/shapely/blob/bc7fa916fc680b43cf58fc206b039e2563ef7a7f/shapely/geometry/base.py#L703)
- [`shapely.predicates.equals_exact(a, b, tolerance=0.0, **kwargs)`](https://github.com/shapely/shapely/blob/bc7fa916fc680b43cf58fc206b039e2563ef7a7f/shapely/predicates.py#L944)
It was noted in https://github.com/shapely/shapely/issues/889#issuecomment-609093066 that tolerance should have a default of 0. Should it?

DEP: change `almost_equals()` to be removed from version 2.0 to 2.1

---

.pre-commit-config.yaml

`flake8` has migrated from GitLab to GitHub, causing the `pre-commit` hook & [linting to fail](https://github.com/jGaboardi/shapely/actions/runs/3479810906/jobs/5818811980#step:4:52). This PR updates `.pre-commit-config.yml`.
xref geopandas/geopandas#2651 (piggybacking @rraymondgh's PR)

CI: flake8 has migrated to GH – update .pre-commit

---

.github/workflows/tests.yml
tests/test_voronoi_diagram.py

The return value has been changed to always be a MultiLineString, instead of either LineString or MultiLineString, depending on the number of input points -> https://github.com/libgeos/geos/pull/702 
This updates the test to reflect that.

CI/TST: fix tests for voronoi_diagram for latest GEOS

---

shapely/tests/test_strtree.py
tests/test_create_inconsistent_dimensionality.py

xref https://github.com/shapely/shapely/pull/1625#issuecomment-1326685177

CI/TST: fix tests for changed numpy error from creating ragged array

---

.circleci/config.yml
.travis.yml

I am having troubles with getting the deployment step in Travis working as we want it (only uploading the wheels it builds, https://github.com/shapely/shapely/pull/1576 didn't work). And in addition the credits on Travis are limited anyway (and will have to be requested again when they are finished). 
So CircleCI seems to be a good alternative to build linux aarch64 wheels (https://cibuildwheel.readthedocs.io/en/stable/#usage).

CI/RLS: set up CircleCI to build Linux aarch64 wheels (instead of Travis CI)

---

.circleci/config.yml

By default CircleCI only runs on pushes to branches, not on tags, so as a result we didn't build the wheels for 2.0rc1 (only on the push that didn't yet have the tag, so that wheel has the wrong version in it). 
In addition also limiting to the main branch.

CI/RLS: ensure to run CircleCI on tags

---

pyproject.toml

This PR ignores a few files from binary wheels that should not be there. The .c, .pxd and .pyx files were not present before #1426.
The curious change of packaging is because the default for include_package_data is different between `setup.py` and `pyproject.toml` metadata structures. Before #1426 the default for `setup.py`'s `include_package_data` was False, but the default for `pyproject.toml`'s `include-package-data` is true ([ref](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#include-package-data)), so it needs to be explicitly set back to false.
Only a few .c, .pxd and .pyx files in .whl files are excluded. Sdist contents are unchanged.

BLD: pin to Cython~=0.29, ignore .c and .pyx files in wheels

---

shapely/tests/test_io.py

This was failing on the s390x arch build on Travis: https://app.travis-ci.com/github/shapely/shapely/jobs/589544603

TST: fix test_to_wkb_flavor to use fixed byte_order to pass on big endian machine

---

.github/workflows/release.yml

Use the stable release branch for the PyPI publish GitHub Action, as recommended in their docs.
See https://github.com/pypa/gh-action-pypi-publish#usage.
This PR replaces #1641.

release CI: Use release/v1 branch for PyPI publish action

---

shapely/tests/test_creation.py
shapely/tests/test_io.py
src/ufuncs.c

GEOS is improving its support for M values (it can now store either XYZ or XYZM buffers under the hood, https://github.com/libgeos/geos/pull/721), and for example can (I think) now also parse WKT or WKB with M values. We will need to update our code to actually make use of those abilities(-> opened https://github.com/shapely/shapely/issues/1648 for this), but this PR just fixes a few test failures because of those changes in GEOS.

TST: fix tests for GEOS changes in M handling

---

.dockerignore
docker/Dockerfile.arm64
docker/Dockerfile.valgrind

Did a run of valgrind and all was passing. But needed a few changes to get it running (from the pygeos -> shapely migration)

DEV: update valgrind Dockerfile

---

shapely/strtree.py

Resolves #1622 
Improves STRtree docstrings in an attempt to make it more clear that the tree is based on 2-dimensional bounding boxes.  Also added a note about tree efficiency, but that might be overkill for the docstring and more appropriate for dedicated documentation on STRtree - which we have not yet created.
/cc @adishavit

DOC: Improve STRtree docstrings

---

src/ufuncs.c

When building with `-Wincompatible-function-pointer-types`, we get a bunch of errors like:
```C
error: incompatible function pointer types initializing 
'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') 
with an expression of type 
'void (*)(char **, npy_intp *, npy_intp *, void *)' (aka 'void (*)(char **, long *, long *, void *)') 
[-Wincompatible-function-pointer-types]
static PyUFuncGenericFunction Y_b_funcs[1] = {&Y_b_func};
^~~~~~~~~
```
This adds the consts needed to silence the error message.

CLN: Add consts to PyUFuncGenericFunction signatures

---

.gitignore

`.gitignore` already includes `*.so`. 
This PR adds also ` *.dylib`, `*.dll` to ignore this binary file types on MacOS and Windows.

ENH:.gitignore - add *.dylib, *.dll to ignore binaries from MacOS and Windows

---

shapely/ops.py

This PR fixes `ops.CollectionOperator.linemerge()` 
There is no such function `shapely.line_merge_directed` 
Fix by replacing with `shapely.line_merge(source, directed=directed)`

BUG: fix directed keyword in shapely.ops.linemerge

---

.github/workflows/tests.yml
shapely/plotting.py
shapely/tests/test_plotting.py

This PR stems from my use case to get a Matplotlib patch from a Shapely polygon, but manipulate it in [my own GUI](https://github.com/sea-bass/pyrobosim) instead of directly plotting it.
This adds a new `patch_from_polygon()` function that is internally called by `plot_polygon()` but can also be used standalone to return a patch without plotting. In the process I also did some slight cleanup.

ENH: Allow getting matplotlib patch from polygon without plotting

---

setup.py

Prepend the current directory to `sys.path` rather than appending it, in order to ensure that the local `versioneer.py` is used.  Otherwise, if one has an incompatible version of `versioneer` installed, the setup script fails, e.g.:
```
$ python -m build -nw
* Getting build dependencies for wheel...
Could not find geos-config executable. Either append the path to geos-config to PATH or manually provide the include_dirs, library_dirs, libraries and other link args for compiling against a GEOS version >=3.5.
Compiling shapely/_geometry_helpers.pyx because it changed.
Compiling shapely/_geos.pyx because it changed.
[1/2] Cythonizing shapely/_geometry_helpers.pyx
[2/2] Cythonizing shapely/_geos.pyx
File …
```

BUG: fix setup.py AttributeError when old versioneer is installed

---

shapely/strtree.py
shapely/tests/common.py
shapely/tests/test_strtree.py

Resolves #1714 
Instead of adding a write lock to the geometry array input to construct the tree, we now take a copy of the input array, which allows the user to modify the input array later without modifying the geometries stored in the tree.

FIX: Copy geometries input to STRtree to prevent modification instead of adding write lock to array

---

.github/workflows/tests.yml
shapely/tests/test_set_operations.py

Skip failing test (`shapely.errors.GEOSException: IllegalArgumentException: Overlay input is mixed-dimension`) with GEOS master till that issue is resolved upstream
Related to: https://github.com/libgeos/geos/issues/797

TST: skip failing test on GEOS master

---

.pre-commit-config.yaml
MANIFEST.in
setup.cfg

I removed the `shapely/example/*` directory a while ago (https://github.com/shapely/shapely/pull/1645), but there were still some references to it.

CLN: remove remaining references to shapely/examples directory

---

.github/workflows/tests.yml
shapely/tests/test_constructive.py
shapely/tests/test_measurement.py
shapely/tests/test_predicates.py

Closes #1345
Closes #1552
Closes #1709
This PR doesn't actually "fix" those issues, but in the meantime those warnings have been fixed upstream in GEOS (https://github.com/libgeos/geos/issues/515, https://github.com/libgeos/geos/pull/791, https://github.com/libgeos/geos/pull/806),a and so this PR updates the tests to no longer suppress the warnings for GEOS >= 3.12 (so we can actually ensure the test suite doesn't generate such warnings). And it also adds some additional cases from the listed issues.

TST: update 'invalid value encountered' floating-point warnings (fixed with GEOS>=3.12)

---

shapely/tests/test_strtree.py

This address [#1729 comment](https://github.com/shapely/shapely/pull/1729#issue-1552080758) and cleans up xfails that were not actually necessary, removes xfails related to GEOS 3.5 (outdated), and removes version guards for < GEOS 3.6 since that is now the min version tested.

TST: Cleanup STRtree xfails & skipifs

---

shapely/_geometry_helpers.pyx
shapely/tests/test_ragged_array.py

Previously calling `shapely.from_ragged_array` on a read-only buffer (such as a coordinates buffer owned by Arrow memory) you'd get an error that the array is read-only
```
File shapely/_geometry_helpers.pyx:96, in shapely._geometry_helpers.simple_geometries_1d()
File stringsource:660, in View.MemoryView.memoryview_cwrapper()
File stringsource:350, in View.MemoryView.memoryview.__cinit__()
ValueError: buffer source array is read-only
```
Since shapely is copying into GEOS memory anyways, it's fine for the buffer to be read-only and only needed to be marked as such with `const`
```py
cdef const double[:, :]
```
I have my editor set to automatically trim trailing whitespace on save. If it's important I can remove the unrelated changes.

FIX: Fix read-only buffer error in `from_ragged_array`

---

.pre-commit-config.yaml

The isort installation for pre-commit is currently failing, xref https://github.com/PyCQA/isort/issues/2077

CI: update isort to fix install error

---

.circleci/config.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.travis.yml
ci/install_geos.sh
shapely/tests/test_misc.py

Update `maint-2.0` to use the latest GEOS minor versions for CI testing.
Also set the version for the binary wheels for the next maintenance release to use GEOS 3.11.2; see [NEWS.md](https://github.com/libgeos/geos/blob/3.11/NEWS.md) for changes.

CI/BLD: update GEOS minor versions

---

docs/geometry.rst
docs/release/2.x.rst
shapely/_geometry.py
shapely/constructive.py
shapely/creation.py
shapely/io.py
shapely/linear.py
shapely/measurement.py
shapely/predicates.py
shapely/set_operations.py

This PR leverages more intersphinx links, and resolves a missing productionlist token warning.
A simplified diff for the repetitive change (113 times) is:
```diff
- For other keyword-only arguments, see the NumPy ufunc docs.
+ See NumPy ufunc docs for other keyword arguments.
```
hopefully this new wording is OK, otherwise suggest a new wording.

DOC: use more intersphinx links

---

shapely/tests/test_io.py

Upstream changes for GEOS 3.12 (current `main`) now use parentheses for MultiPoint sub-members. This change only broke one test. Other changes are expected for the doctests, which should be done when the version of GEOS is changed for doctests.
Xrefs:
- https://github.com/libgeos/geos/pull/903
- https://github.com/libgeos/geos/issues/902

TST: GEOS 3.12 uses parentheses for MultiPoint sub-members

---

docs/index.rst
docs/plotting.rst

Fixes #1712 instead of the closed #1713.
This follows @jorisvandenbossche's suggestion to hard-code the functions in the rst instead of depending on the jinja template.

DOC: include plotting in docs

---

shapely/tests/test_set_operations.py

Essentially reverting the xfail we added in https://github.com/shapely/shapely/pull/1715, as this was fixed upstream in GEOS: https://github.com/libgeos/geos/pull/923

TST: difference set operation works again for mixed dimensions on GEOS main

---

shapely/tests/legacy/test_affinity.py

Those tests passing a numpy array of length 1 to the affine functions were added intentionally in https://github.com/shapely/shapely/pull/794. 
However, the main thing it is testing is that we don't mutate those values inplace, which can also be achieved by using a 0-d (scalar-like) array instead of a 1d array. 
The argument itself is being treated as a scalar by shapely (eg `shapely.affinity.rotate(geom, theta=np.array([10]))`, the `theta` is a scalar), but because of the numpy behaviour of treating a 1d array of length 1 as a scalar, this worked as well. Now that numpy deprecates this in 1.25, I think we can just follow numpy (and let users handle the numpy deprecation warning in a similar way as I am doing here), instead of adding some extra code to keep supporting this 1d array as …

TST: use numpy 0-d instead of 1-d arrays for testing non-mutation of array argument (numpy 1.25 compat)

---

.github/workflows/tests.yml
CHANGES.txt
docs/release/2.x.rst
shapely/geometry/base.py
shapely/geometry/polygon.py
shapely/tests/common.py
shapely/tests/geometry/test_equality.py
shapely/tests/geometry/test_geometry_base.py
shapely/tests/test_geometry.py

Closes https://github.com/shapely/shapely/issues/1732
Broken off from https://github.com/shapely/shapely/pull/1760, to just restore the previous behaviour (using the previous implementaiton) and already add the more extensive tests that I wrote for that PR. This way, the other PR can focus more on the API change.

REGR: fix __eq__ to not ignore z values

---

docs/environment.yml

Since Cython 3.0 was released a few weeks ago, the ReadTheDocs builds have been failing:
```
$ python ./setup.py install --force
...
Error compiling Cython file:
------------------------------------------------------------
...
self.last_error = <char *> malloc((1025) * sizeof(char))
self.last_error[0] = 0
self.last_warning = <char *> malloc((1025) * sizeof(char))
self.last_warning[0] = 0
GEOSContext_setErrorMessageHandler_r(
self.handle, &geos_message_handler, self.last_error
^
------------------------------------------------------------
shapely/_geos.pyx:30:25: Cannot assign type 'void (*)(const char *, void *) except *' to 'GEOSMessageHandler_r'
```
While this is a curious bug to fix for Cython 3.x, the short-term solution is to pin the docs/environment.yml for now. (This error doesn't …

Docs: pin Cython=0.29, geos=3.11, add pip for ReadTheDocs

---

.github/workflows/release.yml
.github/workflows/tests.yml
setup.cfg

I'm working on building Python 3.12 wheels for some of my packages that depend on shapely. It'd be great to have a shapely wheel for Python 3.12.
Side note: I think in pyproject.toml you're supposed to be able to just say "numpy" from 1.25 or 1.26 on. Of course I can't find it now, but I believe it is supposed to be bundled with backwards compatible APIs...I think.

Reenable Python 3.12 wheel building

---

.github/workflows/release.yml
pyproject.toml

* Bump pypa/cibuildwheel from 2.14.1 to 2.16.2
* Don't build manylinux_i686
* Add Python 3.12 classifier

Prepare for Python 3.12 wheels for 2.0.2

---

shapely/geometry/multipolygon.py
shapely/tests/geometry/test_multipolygon.py

… by replacing the check with a `is None` check so that it does not try to make a `bool` out of a `numpy array`. Also added tests to make sure that the `numpy array` creation is now allowed, and added a test for an empty `MultiPolygon` creation to ensure the original behavior is not broken. 
See [#1877](https://github.com/shapely/shapely/issues/1877).

BUG: allow the creation of MultiPolygon from a numpy array of Polygons

---

.circleci/config.yml

We added those for the github actions based workflows, but not yet for CircleCI for Linux aarch64

RLS/BLD: also build Python 3.12 wheels for linux aarch64

---

CHANGES.txt
shapely/tests/geometry/test_format.py
shapely/tests/test_io.py
src/geos.c
src/geos.h
src/pygeom.c
src/ufuncs.c

This is a follow-up to #1907 that considers upstream changes for upcoming GEOS 3.13.0 in https://github.com/libgeos/geos/pull/973
It also fixes a related regression with tests against GEOS main branch, where small non-zero coordinates are shown with scientific notation (with trim enabled) rather than misrepresenting them as zero.

Disable check_to_wkt_trim_compatible for GEOS >= 3.13.0

---

shapely/tests/geometry/test_format.py
shapely/tests/test_strtree.py

This updates tests to work with GEOS main.
Upstream changes from https://github.com/libgeos/geos/pull/978 remove small precision errors from (e.g.) buffered points.

TST: update expected results for GEOS 3.13.0dev

---

src/ufuncs.c

Fixes the following warning by improving `const`-correctness:
```
src/ufuncs.c: In function ‘polygonize_func’:
src/ufuncs.c:2205:51: warning: passing argument 2 of ‘GEOSPolygonize_r’ from incompatible pointer type [-Wincompatible-pointer-types]
2205 |     GEOSGeometry* ret_ptr = GEOSPolygonize_r(ctx, geoms, n_geoms);
|                                                   ^~~~~
|                                                   |
|                                                   GEOSGeometry ** {aka struct GEOSGeom_t **}
In file included from src/geos.h:15,
from src/ufuncs.c:16:
/usr/include/geos_c.h:979:31: note: expected ‘const GEOSGeometry * const*’ {aka ‘const struct GEOSGeom_t * const*’} but argument is of type ‘GEOSGeometry **’ {aka ‘struct GEOSGeom_t **’}
979 |     const …
```

Fix incompatible pointer type passed to GEOSPolygonize_r

---

shapely/plotting.py

`markeredgecolor` was duplicated and marker fill color (`markerfacecolor`) was not represented

DOC: fix plot_points color typo

---

shapely/tests/geometry/test_equality.py
shapely/tests/test_geometry.py

The `test_eq` in `shapely/tests/test_geometry.py` is duplicated with `test_equality` in `shapely/tests/geometry/test_equality.py`
Deduplicating this, and also move the other equality (and hash) related tests in the former file to the latter, which already has more extensive tests on this topic.

TST: move and consolidate Geometry __eq__ tests in geometry/test_equality.py

---

shapely/tests/geometry/test_format.py
shapely/tests/test_strtree.py

This is a manual backport of dba2704cdadbb5745edf9961f97aaf0c60826e42 from #1935 for the `maint-2.0` branch.

TST: update expected results for GEOS 3.13.0dev with maint-2.0

---

.readthedocs.yml

https://github.com/shapely/shapely/pull/1914 is no longer working to get the tags (I suppose because the checkout depth is by default only 50)

DOC: fix version shown on readthedocs (take 2)

---

.github/workflows/release.yml
pyproject.toml

Part of https://github.com/shapely/shapely/issues/1972
And see https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice for a direct link to the NumPy guidelines on updating build dependencies for NumPy 2.0.

BLD: update build-system requires to use latest numpy instead of oldest-supported-numpy + build nightly wheels with numpy nightly

---

.circleci/config.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.travis.yml
CHANGES.txt
shapely/constructive.py
shapely/tests/test_set_operations.py

Adapted backport of https://github.com/shapely/shapely/pull/1942 to the maint-2.0 branch, using GEOS 3.11.3 instead of 3.12.1 for the wheels.

MAINT: update to latest GEOS point release in CI (and GEOS 3.11.3 for wheels) (#1942)

---

.circleci/config.yml
.github/workflows/release.yml
pyproject.toml

See https://github.com/shapely/shapely/issues/1972 for the details.
Current Shapely wheels for 2.0.x (and for an upcoming 2.0.3 release) are not compatible with future numpy 2.0 packages (if you install shapely now in an environment with nightly numpy, it fails to import), therefore it is recommended to add this upper pin now for releases. 
We will keep the more flexible pin on the development branch, assuming by the time we release shapely 2.1, numpy 2.0 will be out and we can build shapely 2.0 to be compatible with all numpy versions.

COMPAT: Add a numpy<2 pin to install requirements for 2.0.x

---

shapely/algorithms/_oriented_envelope.py
shapely/constructive.py
shapely/tests/common.py
shapely/tests/test_constructive.py

Closes https://github.com/shapely/shapely/issues/1929
In the end I thought to use `np.frompyfunc` and remove the manual iteration, instead of just fixing that single check for when to use the iteration code path. This ensures that it will work consistently with numpy in what it accepts (the kinds of array likes), and also that it will return the array like objects if those implement the numpy protocols (eg in shapely 2.0.1, calling this function on a geopandas.GeoSeries will also return a GeoSeries)

REGR: ensure oriented_envelope (GEOS<3.12 code path) accepts array-like with ufunc protocol

---

CHANGES.txt
shapely/constructive.py
shapely/tests/test_constructive.py
src/fast_loop_macros.h
src/ufuncs.c

Exposes the option from GEOS 3.12 allowing deterministic order of polygons within the GeometryCollection that is an output of the `voronoi_polygons` (see https://github.com/libgeos/geos/pull/781). Without it, the order is not possible to link to original geometries without using a spatial join.
Where is the best to put a test? I've noticed only some generic tests of `voronoi_polygons` in `test_constructive.py` and legacy tests of `ops.voronoi_diagram`.
Closes #981

ENH: add ordered option to voronoi_polygons

---

.github/workflows/release.yml

Use native Apple Silicon macOS runners ([described here](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)) to build arm64 wheels.
Also, remove `universal2` wheels, since I think it's fine to have separate `x86_64` builds for macOS.

RLS/BLD: use native Apple Silicon macOS for arm64 wheels; remove universal2

---

shapely/decorators.py
shapely/tests/test_misc.py

Fixes #1937.
I’m not thrilled with this, particularly with the unexplained `extra_indent`, but it does successfully match the behavior in Python 3.13.0a1.
For reference, here’s the current implementation of `_PyCompile_CleanDoc()`:
https://github.com/methane/cpython/blob/9c03215a3ee31462045b2c2ee162bdda30c54572/Python/compile.c#L7816

TST: Adjust tests and require_geos decorator implementation for docstring indent stripping in Python 3.13

---

.github/workflows/release.yml

Follow-up on https://github.com/shapely/shapely/pull/1997, as apparently the action only works on ubuntu, so we need to run it once after all wheels builds succeeded

Fix uploading of nightly wheels

---

shapely/io.py
shapely/tests/common.py
shapely/tests/test_io.py
shapely/wkt.py
src/pygeom.c

Working towards #1648 as a first step, to enable outputs with M or ZM dimensions. This requires GEOS 3.12+, which <s>is currently under development</s> was released 2023-06-27.
Earlier supported GEOS versions have always had limited support for reading these geometries:
- WKT will parse XYM geometries like `POINT M (1 2 4)` as XYZ, incorrectly interpreting M values as Z values
- WKT will parse XYZM geometries like `POINT ZM (1 2 3 4)` as XYZ, ignoring M values
- WKB will parse XYM geometries as XY, ignoring M values
- WKB will parse XYZM geometries as XYZ, ignoring M values
With GEOS 3.12+, the default `output_dimension` is adjusted from 3 to 4. Under the hood, this uses `GEOSWKBWriter_setOutputDimension_r` or `GEOSWKTWriter_setOutputDimension_r` to output XYZ, XYM or XYZM geometries. …

ENH: Enable M and ZM in WKT and WKB outputs

---

shapely/testing.py

Recent change in numpy main with different semantics for the `copy` keyword, where `copy=False` will now guarantee (instead of try) to not make a copy, and thus raise an error when it cannot create the array without allocating data.

COMPAT: fix assert_geometries_equal to work with numpy 2.0 copy changes

---

docs/installation.rst

Follow-up on https://github.com/shapely/shapely/pull/1997 / https://github.com/shapely/shapely/pull/1998.
I still need to update the tags to make this actually work. Currently, those wheels have versions like 2.0.1+78 (after 2.0.1, we branched for maint-2.0).
To make this more usable (so the wheels have a version number that is considered higher than the released version 2.0.3, and gets preferred by pip when specifying the index), I think we will have to add a `2.1.0.dev0` tag to the main branch (e.g. on the commit just after we branched maint-2.0)

DOC: document how to install nightly wheels

---

shapely/tests/test_io.py
src/ufuncs.c

This fixes an issue while using `to_wkt` as a ufunc on an array with GEOS >= 3.9.0 with empty geometries. The issue (discovered with GH-2004) is that the WKT writer finishes sometimes too early while processing geometries.
For instance, using shapely 2.0.2 with GEOS 3.12.1 via conda-forge:
```python
import shapely
empty_geoms = shapely.from_wkt(["POINT Z EMPTY", "POINT Z EMPTY"])
list(shapely.to_wkt(empty_geoms))
```
It also seems that there could be a missing `Py_XDECREF(*out);`, but I'd appreciate someone with Python C API expertise to weight in.
This can be backported to `maint-2.0` too.

FIX: to_wkt with empty Z geometry arrays

---

docs/manual.rst
shapely/_geometry.py
shapely/geometry/base.py
shapely/predicates.py
shapely/tests/test_io.py
shapely/tests/test_predicates.py
src/ufuncs.c

Add a basic `has_m` unary predicate function, available with GEOS >= 3.12.0.
* Update some related docs for `get_coordinate_dimension`
* Add `has_z` to `UNARY_PREDICATES` for shapely/tests/test_predicates.py

ENH: add has_m

---

shapely/tests/test_io.py
src/geos.c
src/geos.h
src/pygeom.c
src/ufuncs.c

This uses `wkt_empty_3d_geometry` only for GEOS >= 3.9.0 and < 3.12.0, otherwise it is not defined or used.
Closes #2004

FIX: fix WKT for empty M and ZM geometries

---

.github/workflows/release.yml
ci/install_geos.sh

_If_ this works, it might be a bit cleaner (from https://github.com/isciences/exactextract/pull/87)

BLD: use geos INSTALL_NAME_DIR for MacOS instead of specifying custom LDFLAGS with rpath

---

shapely/constructive.py
shapely/coordinates.py
shapely/creation.py
shapely/geometry/base.py
shapely/predicates.py

xref https://github.com/shapely/shapely/issues/1994#issuecomment-1987266626
With the upcoming 2.0 release, I think it will be nice to start documenting more explicitly when keywords or entire functions are new (I think it will be normal to require any >= 2, and when doing that you can only use features that already existed in 2.0).
Sphinx has a `versionadded` directive for this, and so this PR is adding that to the relevant places for 2.1.
If we like this, we should also try to think about doing this directly in PRs adding the new features.

DOC: add versionadded note to new functions or keywords for 2.1

---

docs/manual.rst
shapely/_geometry.py
shapely/geometry/point.py
shapely/tests/geometry/test_point.py
shapely/tests/test_geometry.py
src/ufuncs.c

Adds `get_m` and a `m` point property, available with GEOS 3.12 or later. For example:
```python
import shapely
assert shapely.geos_version[0:2] >= (3, 12), shapely.geos_version_string
pt = shapely.from_wkt("POINT M (1 2 4)")
assert pt.m == shapely.get_m(pt) == 4.0
```
And similar to the `z` property:
```python
pt = shapely.geometry.Point(1, 2)
shapely.get_m(pt)  # nan
pt.m
```
Other checks to `shapely/tests/geometry/test_point.py` will be added after reworking `Point()`.

ENH: get_m and point.m property

---

.github/workflows/release.yml
.github/workflows/tests.yml
pyproject.toml
shapely/testing.py

See https://github.com/shapely/shapely/issues/1972 for overview of the numpy 2.0 compatibility. Now that there is a numpy 2.0 rc with a stable ABI, packages are encourages to make a new release that is compatible with the upcoming numpy 2.0 with compatible wheels.
This PR is to make the 2.0.x branch compatible with numpy 2.0 (for a 2.0.4 release), and is essentially a (partial) backport of
* https://github.com/shapely/shapely/pull/1974/
* https://github.com/shapely/shapely/pull/2007
* https://github.com/shapely/shapely/pull/1973

BLD: update build-system requires to use latest numpy instead of oldest-supported-numpy - build wheels with numpy 2.0

---

shapely/_ragged_array.py
shapely/tests/test_ragged_array.py

Currently, if you have missing values (`None`) in an array of Points and convert it to a ragged array, the resulting array is not of the same length as the input:
```
>>> import shapely
>>> arr = shapely.from_wkt(["POINT (1 1)", None, "POINT (3 3)"])
>>> shapely.to_ragged_array(arr)[1]
array([[1., 1.],
[3., 3.]])
```
while in case of _empty_ points we ensure to insert NaNs in the resulting array:
```
>>> arr = shapely.from_wkt(["POINT (1 1)", "POINT EMPTY", "POINT (3 3)"])
>>> shapely.to_ragged_array(arr)[1]
array([[ 1.,  1.],
[nan, nan],
[ 3.,  3.]])
```
This is buggy. First, it makes it awkward to roundtrip or use the resulting values to convert to (Geo)Arrow data, because for Points (which uses a fixed size list type in Arrow), we assume the ragged array is of exactly the same length. …

BUG: fix to_ragged_array for Points with missing values

---

CHANGES.txt
docs/conf.py
docs/installation.rst
docs/migration_pygeos.rst
docs/release/2.x.rst
pyproject.toml
shapely/_geometry_helpers.pyx
shapely/creation.py
shapely/io.py
shapely/plotting.py
shapely/predicates.py
shapely/tests/geometry/test_format.py
shapely/tests/test_geometry.py
shapely/tests/test_linear.py
shapely/tests/test_predicates.py
shapely/tests/test_set_operations.py
src/coords.c
src/geos.c
src/strtree.c
src/ufuncs.c

Most are in comments; some are in user-visible places like changelogs and doc-strings.
I noticed a typo in a comment in `pyproject.toml` while updating the [`python-shapely` package](https://src.fedoraproject.org/rpms/python-shapely) in Fedora; I used [`codespell`](https://github.com/codespell-project/codespell) to help me find others.

Fix a number of minor typos

---

docs/geometry.rst
shapely/_geometry.py
shapely/constructive.py

Improvements to `set_precision` documentation:
- it changes the order of points,... which doesn't seem to be expected to happen. So better to mention this explicitly in its documentation.
- some more clarification on what `set_precision` does, e.g. the collapsing of narrow parts of polygons.
The "canonical form" also isn't documented in detail... so this PR tries to solve this as well.
Resolves #1950 
Resolves #1952

DOC: improve documentation of canonical form and set_precision

---

.github/workflows/tests.yml

Installing python with a x64 architecture stopped working with `macos-latest` (https://github.com/actions/setup-python/issues/855#issuecomment-2096792205), so as a quick workaround specifically asking for macos-13 runner instead (longer term we should check how to run with latest macos, but that requires changing the set up of the `architecture` matrix entry a bit)

CI: use macos-13 for tests to run x64 python

---

shapely/coords.py
shapely/tests/geometry/test_coords.py

Recent CI failures have picked up a recent NumPy 2.0 change, noted in the migration guide under ["Adapting to changes in the copy keyword"](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword).
A simple fix appears to be to simply add `copy=None` to the `__array__` signature. This value is not used by the method.
---
[Here is an example failure](https://github.com/shapely/shapely/actions/runs/9070802200/job/24923285344#step:16:178):
```
________________________ TestCoords.test_data_promotion ________________________
self = <shapely.tests.geometry.test_coords.TestCoords object at 0x7f6bbc72fb90>
def test_data_promotion(self):
coords = np.array([[12, 34], [56, 78]], dtype=np.float32)
>       processed_coords = np.array(LineString(coords).coords) …
```

ENH: add copy=None to CoordinateSequence.__array__

---

.github/workflows/release.yml

According to the 2024 GitHub Actions macOS runner image roadmap, macos-11 is removed. Macos-12 will be deprecated next month, so it could make sense to jump to macos-13.

CI: Update macos-11 image to macos-13

---

MANIFEST.in
setup.py

This PR replaces setuptools' deprecated [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) module with a simple function to compare versions as tuples.
Expressions like this should be fine: `assert version_tuple("3.8") < version_tuple("3.13.0dev")`
Other changes:
- Replace `subprocess.Popen` with simpler `subprocess.run`
- Prepend `numpy.get_include()` rather than append, otherwise system libs (e.g. [`/usr/include/python3.10`](https://packages.ubuntu.com/jammy/amd64/python3-numpy/filelist)) will take precedence over locally/venv installed libs. This is important while developing for new numpy 2.0 libs.
- The `tests` subdir was moved, so remove from MANIFEST.in

BLD: replace pkg_resources, prepend numpy include dirs

---

.github/workflows/release.yml

Partial revert of https://github.com/shapely/shapely/pull/1974, now that stable numpy 2.0 is out, we don't have to go through those extra hoops to get the 2.0rc prerelease installed in the wheel building process.
xref https://github.com/shapely/shapely/issues/1972

BLD/CLN: clean-up wheel build setup now numpy 2.0 final is out

---

shapely/affinity.py

This partially reverts #1418 with a more manual matrix multiplication method used previously. Some of the stack and transpose aspects are simplified.
Closes #2066

FIX: replace matmul with manual matrix multiplication for affinity

---

.circleci/config.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.travis.yml
shapely/constructive.py

This upgrades a few components for CI testing and the GEOS version used in binary wheels for the shapely 2.0 maintenance branch.
- Shapely-2.0.5 is expected soon and will have GEOS 3.11.4; see [changes](https://github.com/libgeos/geos/blob/3.11.4/NEWS.md)
- Add a "2024" CI matrix entry with numpy-2.0.0 <s>and python-13 (currently beta)</s> (hold off until numpy has cp313 binary wheels)
- Add test with macos-14 for an apple silicon runner
- Fix doctests for geos-3.11.4 (and older 3.11.x)

RLS/CI: upgrade GEOS versions to latest minor, add more to CI matrix

---

CHANGES.txt
CITATION.cff
docs/release/2.x.rst

The next minor version of the 2.0.x series is anticipated sometime today.

DOC/RLS: starts changelog for 2.0.5

---

shapely/geometry/base.py
shapely/tests/geometry/test_geometry_base.py

Similar to #2074, this PR restores [`line.project(point)`](https://shapely.readthedocs.io/en/stable/manual.html#object.project) to return a Python float, and not a NumPy float64 scalar.  It similarly changes `line_locate_point` as well.
This is more obvious with NumPy 2.0:
```pycon
>>> import shapely
>>> line = shapely.from_wkt("LINESTRING (0 0, 1 0)")
>>> point = shapely.from_wkt("POINT(0 1)")
>>> line.project(point)
np.float64(0.0)
>>> line.line_locate_point(point)
np.float64(0.0)
```
this PR changes the functions to return Python float(0.0) instead (or `0.0`).
Tests are improved to check other scalar results, and test `project` and `interpolate` function aliases too.

BUG: fix base geometry "project" to return Python float

---

.github/workflows/tests.yml
shapely/tests/legacy/test_operations.py
shapely/tests/legacy/test_predicates.py
shapely/tests/test_strtree.py

Follows #2086 to finally enable testing of Python 3.13 with NumPy 2.1. Currently, both these are available as release candidates. Also note that NumPy 2.0.x does not have any binary wheels out for Python 3.13.
I'm not sure when GEOS 3.13 is ready, but this would ideally be put under the "2024" item too when it's out.

TST/CI: enable testing Python 3.13, NumPy 2.1, GEOS 3.13

---

.github/workflows/release.yml

Starting with clang 16 ([announcement](https://discourse.llvm.org/t/clang-16-notice-of-potentially-breaking-changes/65562)), it started to default `-Wincompatible-function-pointer-types` to be on. This causes a bunch of hard errors in the wheel build for MacOS arm64 on the macos-14 image, like:
```
src/ufuncs.c:213:47: error: incompatible function pointer types initializing 'PyUFuncGenericFunction' (aka 'void (*)(char **, long *, long *, void *)') with an expression of type 'void (*)(char **, const npy_intp *, const npy_intp *, void *)' (aka 'void (*)(char **, const long *, const long *, void *)') [-Wincompatible-function-pointer-types]
static PyUFuncGenericFunction Y_b_funcs[1] = {&Y_b_func};
^~~~~~~~~
```
In this case it seems to be the issue of `const long *` vs `long *`.
This could …

BLD: suppress 'incompatible-function-pointer-types' error for clang>=16

---

CHANGES.txt
CITATION.cff
docs/release/2.x.rst

The next minor version of the 2.0.x series is anticipated sometime today, to fix compatibility with the just released numpy 2.1.0 (https://github.com/shapely/shapely/pull/2099)

DOC/RLS: starts changelog for 2.0.6

---

shapely/set_operations.py

This is a minor fix of docstring to fix the error of API documentation.
- https://shapely.readthedocs.io/en/latest/reference/shapely.coverage_union.html#shapely.coverage_union

DOC: Add blank line at docstring to fix the error of API documentation

---

docs/manual.rst
shapely/geometry/linestring.py

The validity test is meaningful for more than Polygons and MultiPolygons, as LineStrings with zero length can be created and are invalid. This PR corrects the manual.

DOC: LineStrings with zero length are invalid

---

.github/workflows/tests.yml
README.rst
docs/manual.rst
setup.py
shapely/io.py
shapely/linear.py
shapely/set_operations.py
shapely/tests/geometry/test_equality.py
shapely/tests/geometry/test_geometry_base.py
shapely/tests/legacy/test_pickle.py
shapely/tests/legacy/test_wkb.py
shapely/tests/test_constructive.py
shapely/tests/test_coordinates.py
shapely/tests/test_creation.py
shapely/tests/test_geometry.py
shapely/tests/test_io.py
shapely/tests/test_linear.py
shapely/tests/test_misc.py
shapely/tests/test_set_operations.py
shapely/tests/test_testing.py
src/geos.c
src/geos.h
src/pygeom.c
src/ufuncs.c

GEOS 3.8.4 reached it's EOL on 2023/11/12, thus it should be dropped for shapely's main branch.
The CI test matrix is substituted with GEOS 3.9.0 for now, as the number of combinations need to also include Python versions too (see #2119).
Many of the tests are simplified to remove conditionals.
<s>The C lib also contains some important corrections, which I may bring as a backport for maint-2.0.</s> (Update: the corrections only apply to main, thus should not be backported). There were some partially removed GEOS 3.7 features from #1885 that need refining, e.g. the def for `GEOS_SINCE_3_8_0` was removed, but there were still active blocks that used that def, now handled in this PR.

MAINT: Drop GEOS 3.8

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/tests.yml
CHANGES.txt
README.rst
asv.conf.json
docs/release/2.x.rst
pyproject.toml
shapely/geometry/base.py
shapely/geometry/polygon.py
shapely/strtree.py

A first step following https://github.com/shapely/shapely/issues/2119 (after also dropping GEOS 3.8 in https://github.com/shapely/shapely/pull/2124), dropping at least Python 3.8.

MAINT: drop Python 3.8 support

---

pyproject.toml

Now that we only support Python >= 3.9, we can remove the oldest-supported-numpy entirely. 
And also added a rough upper pin on numpy<3, because a numpy 3 would probably again mean ABI breaking changes that would require a re-build of packages.

MAINT: clean-up numpy build dependency in pyproject.toml

---

.github/workflows/tests.yml
setup.py
shapely/_geometry_helpers.pyx
shapely/_geos.pyx
src/c_api.c
src/coords.c
src/geos.c
src/geos.h
src/lib.c
src/pygeom.c
src/pygeos.c
src/strtree.c
src/ufuncs.c
src/vector.c

This refactors the setuptools-based build with a few changes:
- Rename `get_geos_paths()` to `get_ext_options()`, which also embeds NumPy include dir.
- Also use `define_macros` (aka `-D`) for `GEOS_USE_ONLY_R_API`, `NPY_NO_DEPRECATED_API`, and `NPY_TARGET_VERSION`
- Remove custom `build_ext` cmdclass, which used to embed NumPy include dir. This references a PR from 8 years ago as a workaround for some issue that is probably historic by now (although I don't fully understand what the issue was)
- Use ruff check / format on setup.py to bring it to the same standard as other Python sources
- Resolve a few basic C-level warnings; there are still other unresolved warnings
- Remove macros from source files, as they are moved to `define_macros` in setup.py
- Add `-v` for verbose builds in CI to …

BLD: refactor setup.py, consolidate define_macros, cleanup warnings

---

.github/workflows/tests.yml

Test latest deps, released today.
Holding until geos-3.13 is released, then I'll modify this PR.

TST: minor bump to geos-3.13.0 and numpy-2.1.1

---

CHANGES.txt
shapely/tests/test_io.py
src/ufuncs.c

Fixes https://github.com/shapely/shapely/issues/2111
Serialization of empty points in GEOS has been fixed in [3.10.2](https://github.com/libgeos/geos/blob/7cb33c988bb0115f4fe107785570ae5786ed2401/NEWS#L73), so I updated the C code and tests to handle that.

BUG: fix to_geojson with empty point

---

shapely/geometry/multilinestring.py
shapely/geometry/multipoint.py

Closes #2122
This avoids the warning if the sequence of points/lines being passed is a pandas series. I didn't add a test that covers the original use case, because that would require pandas and for now we don't have any optional (geo)pandas usage in the tests, which would be good to keep that way. 
But I think it is also a valid python code simplification in itself.

COMPAT: MultiPoint/LineString constructor to iterate directly over in put to avoid getitem access

---

CHANGES.txt
shapely/geometry/point.py
shapely/tests/geometry/test_point.py

Fixes https://github.com/shapely/shapely/issues/1807
Empty points coordinates are convert to an empty tuple. This is in line with how GEOS and PostGIS serialize empty points as GeoJSON (`{"type":"Point","coordinates":[]}`.

FIX: mapping of empty point

---

shapely/predicates.py
shapely/tests/test_predicates.py

Closes #1734
See https://github.com/shapely/shapely/issues/1726#issuecomment-1399434147 for example of performance impact
Still need to update the docstring, if we want to do this.

PERF: prepare single geometry input to contains_xy and intersects_xy

---

.github/workflows/release.yml
.github/workflows/tests.yml
pyproject.toml
setup.py
src/lib.c

This declares the package as supporting nogil Python releases. I have tested it locally and it works as expected. Without this I get a warning that shapely doesn't support the nogil free threading, without this it runs as expected and passes the tests.
Some links for information on what I am updating here.
Update to the module definition:
https://py-free-threading.github.io/porting/#__tabbed_1_1
CI testing:
Added installation from the deadsnakes setup-python version, which I think will only work on the ubuntu runner:
https://py-free-threading.github.io/ci/
cibuildwheel support to build the free threaded wheels:
https://cibuildwheel.pypa.io/en/stable/options/#free-threaded-support
xref: #2137

MNT: Add Python 3.13t free threading support to the extensions

---

docs/manual.rst

This PR improves the clarity of the user manual by updating sections where the word 'copy' is used, to be more precise. In version 1, all copies were deep, but with version 2 having immutable geometry objects some operations are now simply return references, but not all.
Fixes https://github.com/shapely/shapely/issues/2195

DOC: Be specific about copy operations in the user manual

---

.github/workflows/release.yml

The latest [numpy release files](https://pypi.org/project/numpy/#files) all use `musllinux_1_2*` images.

BLD: use musllinux_1_2_x86_64 image

---

CHANGES.txt
CITATION.cff
docs/conf.py
docs/release/2.x.rst

For doing a quick 2.0.7 (https://github.com/shapely/shapely/issues/2208)

DOC/RLS: starts changelog for 2.0.7

---

shapely/geometry/polygon.py
shapely/tests/legacy/test_orient.py

I recently had a user run into an error they couldn't figure out. Upon analyzing the issue, I pinpointed it to a very simple use case of trying to call `shapely.geometry.polygon.orient()` on an empty `Polygon` as follows:
```python
from shapely.geometry import Polygon
from shapely.geometry.polygon import orient
orient(Polygon())
```
This yields the following error:
```
File "<stdin>", line 1, in <module>
File "/home/sebastian/python-virtualenvs/pyrobosim/lib/python3.12/site-packages/shapely/geometry/polygon.py", line 346, in orient
if signed_area(ring) / s >= 0.0:
^^^^^^^^^^^^^^^^^
File "/home/sebastian/python-virtualenvs/pyrobosim/lib/python3.12/site-packages/shapely/algorithms/cga.py", line 11, in signed_area
xs, ys = np.vstack([coords, coords[1]]).T …
```

BUG: Gracefully handle calling orient() on empty polygon

---

docs/release/1.x.rst
docs/strtree.rst

These were the only misspellings I found.

STRtree: fix capitalization in the docs

---

.github/workflows/tests.yml
CHANGES.txt
README.rst
docker/Dockerfile.valgrind
docs/release/2.x.rst
pyproject.toml
shapely/coordinates.py
shapely/ops.py
shapely/strtree.py

As discussed in https://github.com/shapely/shapely/issues/2119, similar like https://github.com/shapely/shapely/pull/2127 for Python 3.8.

MAINT: drop Python 3.9 support

---

shapely/tests/test_constructive.py
shapely/tests/test_io.py

This PR allows older point-releases of GEOS to be successfully tested with shapely, usually by skipping over older upstream bugs and expected behaviours. For example [GEOS 3.10.2 on Ubuntu jammy](https://packages.ubuntu.com/jammy/libgeos-c1v5) previously raise a segfault.
I've manually checked this PR with a few GEOS version ranges (linux x64 only):
- GEOS 3.9.0 to 3.9.5 ([NEWS](https://github.com/libgeos/geos/blob/3.9/NEWS))
- GEOS 3.10.1 to 3.10.6 (not including GEOS 3.10.0) ([NEWS](https://github.com/libgeos/geos/blob/3.10/NEWS))
- GEOS 3.11.0 to 3.11.4 ([NEWS.md](https://github.com/libgeos/geos/blob/3.11/NEWS.md))

TST: fix testing with older GEOS versions (3.9 to 3.11)

---

shapely/coordinates.py
shapely/decorators.py
shapely/tests/test_coordinates.py
src/coords.c
src/geos.c
src/lib.c
src/pygeos.c

This enhancement allows `shapely.get_coordinates()` to get M coordinate data with `include_m=True`. For shapely 2.1, this argument is after the keyword-only (`, *,`) marker. A DeprecationWarning is shown if the function is called with positional arguments for `include_z` or `return_index`, since a future version of shapely may require these as keyword-only. In the code I'm suggesting this be changed to a keyword-only signature with shapely 2.2, but this change schedule can be postponed later if needed.
From a low-level API, here are some notes:
- No changes to [`coordseq_to_buffer(..., int has_z, int has_m)`](https://github.com/shapely/shapely/blob/d62b3a9cfc35638789b4a31d2e83bad672a0753f/src/geos.h#L209-L210) which has a compatible signature with `has_m`.
- Change `GetCoords()` and …

ENH: Add `include_m` to `get_coordinates`, warn with positional args

---

docs/manual.rst

Pretty sure this isn't right. LinearRing instances can be constructed using a sequence of points, like LineStrings

DOC: fix typo in LinearRing manual - can be constructed using a sequence of Points

---

shapely/_ragged_array.py
shapely/tests/common.py
shapely/tests/test_ragged_array.py

This enhancement allows [`to_ragged_array()`](https://shapely.readthedocs.io/en/2.0.7/reference/shapely.to_ragged_array.html) to get M coordinate data with `include_m`, which behaves similar to `include_z`, where it can be None (default), False or True. Setting `include_m=True` with GEOS<3.12.0 will get all NaN coordinate data, as these GEOS versions don't support geometries with M dimensions.
The tests `test_include_z` and `test_include_z_false` are replaced with `test_to_ragged_array(geom, include_z, include_m)` with all combinations of parameters, including XYM and XYZM geometries for GEOS >= 3.12.0.
A minor unrelated fix is to correct a typo: `stringt` -> `string`.
Next steps:

ENH: Add `include_m` to `to_ragged_array`

---

shapely/coords.py
shapely/geometry/base.py
shapely/tests/geometry/test_coords.py

This minor fix is an oversight related to #2234 where M coordinates should appear in the `.coords` property if present in the geometry.

FIX: allow .coords to include M coordinates if present

---

shapely/_geometry.py
shapely/constructive.py
shapely/coordinates.py
shapely/creation.py
shapely/decorators.py
shapely/geometry/base.py
shapely/geometry/linestring.py
shapely/linear.py
shapely/ops.py
shapely/predicates.py
shapely/set_operations.py
shapely/tests/geometry/test_format.py
shapely/tests/geometry/test_geometry_base.py
shapely/tests/geometry/test_linestring.py
shapely/tests/geometry/test_polygon.py
shapely/tests/legacy/test_operations.py
shapely/tests/test_constructive.py
shapely/tests/test_coordinates.py
shapely/tests/test_creation.py
shapely/tests/test_creation_indices.py
shapely/tests/test_geometry.py
shapely/tests/test_linear.py
shapely/tests/test_set_operations.py

This adds a few deprecation warnings to a few functions:
- `shapely.transform()` - warns about positional `include_z`, also described in docs
- `shapely.points()` - warns about positional `indices`
- `shapely.linestrings()` - warns about positional `indices`
- `shapely.linearrings()` - warns about positional `indices`
The last three creation functions don't note the deprecation warning, as I'm guessing it's not commonly used? <s>The tests appeared to be missing use with indices, so these tests are added (both as positional and keyword).</s> (Found the creation tests with "indices" in a separate test file.)
Xref to #2234 that introduced the decorator function and raised warnings for `shapely.get_coordinates`.
Are there any other public functions that have positional arguments that should …

DEPR: deprecate positional args in some functions

---

shapely/geometry/base.py
shapely/tests/legacy/test_equality.py

This removes `BaseGeometry.almost_equals()` as it has noted for a few years that it will be removed for shapely 2.1.
There are a few relevant xrefs:
- #1555 (ping @snowman2)
- #1604
- 26cafd027ab26a6b728ce8a3d26f0b9c8b114bf1
Is there anything further to consider? Or just remove it? (I have no string opinions on the matter, just reviewing 2.1 deprecations)

DEPR: remove BaseGeometry.almost_equals()

---

shapely/geometry/base.py
shapely/tests/legacy/test_buffer.py

Back in shapely-1.8, the `BaseGeometry.buffer()` function used `resolution=`
https://github.com/shapely/shapely/blob/9cf3cdfae7c9aa01b56c7151a51e6a517cceabdd/shapely/geometry/base.py#L541-L543
Since shapely-2.0 this has been renamed `quad_segs=`. This shows a FutureWarning if `resolution` is used.

DEPR: deprecate 'resolution' argument for BaseGeometry.buffer()

---

shapely/ops.py
shapely/tests/legacy/test_union.py

This removes `cascaded_union()`, which has been deprecated since shapely 1.8
Related xrefs:
- #715
- #1025

DEPR: remove deprecated cascaded_union() method

---

shapely/_ragged_array.py
shapely/tests/test_ragged_array.py

Closes https://github.com/shapely/shapely/issues/1745
It appears that we now already support this (because of the new cython implementation, https://github.com/shapely/shapely/pull/2142 and https://github.com/shapely/shapely/pull/2225), so just adding tests.

TST: support sliced offsets in from_ragged_array

---

shapely/errors.py
shapely/geometry/base.py
shapely/speedups.py

Those are deprecations that were already introduced in shapely 2.0. I think we can move those to a more visible FutureWarning now before actually removing them later.

DEPR: bump some DeprecationWarnings from shapely 2.0 to more visible FutureWarning

---

shapely/tests/legacy/test_pickle.py
src/pygeom.c

This refactor postpones shapely <2 geometry pickle doomsday for a future shapely release. There's no rush to remove this support, as it works and is used "out in the wild".
Closes #2242

REF: postpone shapely <2 geometry pickle doomsday

---

shapely/tests/test_creation.py
shapely/tests/test_creation_indices.py

This is a relatively minor renaming of tests for the `handle_nan` option, which makes them more consistent, something along the lines of:
def test_<geomtype>_handle_nan_<option>[_<behaviour]([args]):
There is also a minor fix for a geometry type in `test_linearrings_invalid_ndim` which I've stumbled on while developing M support for linestrings (for 2.2).

TST: rename tests that use `handle_nan` option

---

shapely/set_operations.py
shapely/tests/test_set_operations.py

See https://github.com/shapely/shapely/issues/2027 for more context: the `symmetric_difference_all` has wrong behaviour which is not easy to fix, so rather deprecate and remove this function for now.

DEPR: deprecate symmetric_difference_all

---

CHANGES.txt
docs/release/2.x.rst
shapely/_coverage.py
shapely/io.py
shapely/predicates.py

Starting to update the release notes for 2.1.0. For now adding some missing things and aligning CHANGES.txt and 
docs/release/2.x.rst (some things were only added in one of both). 
If we follow the same approach as for 2.0.0, we could further expand the doc page a bit more (e.g. add an explicit section about M support or about coverage support), and at the same time reduce the content in CHANGES.txt. But also happy to keep both in sync (although it is not great to have to keep both)

DOC/RLS: update changelog notes for 2.1.0 release

---

docs/coverage.rst

Exposing these on coverage-dedicated API reference page to keep all relevant functions visible from a single place. Keeping it also in set operations page as it belongs to both and will have better discoverabilty that way.

DOC: add coverage_union to coverage API page

---

.github/workflows/tests.yml
docs/geometry.rst
docs/manual.rst
docs/migration.rst
shapely/io.py

There are multiple objectives of this PR:
- Change CI job to run doctests with Python 3.13, GEOS 3.13.1 and NumPy 2.1.3 (finally makes use of [#2200](https://github.com/shapely/shapely/pull/2200))
- Add CI checks for the other RST docs, which required some minor refactoring to pass
- Remove the advanced sorting example from the manual, since this [only worked "by accident" until Python 3.13](https://github.com/shapely/shapely/issues/2251#issuecomment-2700093910)
- Add a formatting subsection on scientific formatting in WKT, with a bit of re-wording to the "semantic for format specification" section
- Re-word some of the migration guideline, as shapely 2.0 is now a past release (i.e. no longer "upcoming")
Closes #2251
Closes #2275

DOC/TST: remove broken sort, several updates, more doctests

---

shapely/decorators.py
shapely/tests/test_decorators.py

Closes https://github.com/shapely/shapely/issues/2282
Closes https://github.com/shapely/shapely/issues/2280
It's my first time contributing here.
- I'm aware that shapely is generally untyped.
- Types used here are very similar to shapely/strtree.py, and because of that I decided to include them.
- **Allow edits by maintainers** is checked so feel free to push commits for minor issues
Potentially useful info for reviewers:
`__code__` docs reference (from Python 3.9): https://docs.python.org/3.9/library/inspect.html
- co_argcount: number of arguments (not including keyword only arguments, * or ** args)
- co_varnames: tuple of names of arguments and local variables
This lets us skip the heavy inspect logic.
Another big optimization is the `n > warn_from` check and LRU cache of the messages, …

ENH: improve performance of deprecate_positional

---

shapely/_geometry_helpers.pyx
shapely/tests/test_ragged_array.py

Noticed some other issues while investigating https://github.com/shapely/shapely/discussions/2284, it was easy to pass invalid offset data. While we can do some cheap checks to avoid wrong data or crashes later down the line if a user is passing wrong data.

Better input validation in from_ragged_array

---

shapely/tests/legacy/test_polylabel.py
shapely/tests/test_constructive.py

Some tests are failing on the GEOS main builds (eg https://github.com/shapely/shapely/actions/runs/14814815121/job/41593981112), related to some recent commits in GEOS (https://github.com/libgeos/geos/compare/4ae3f0536735923dc93d6ea8a1e0dadafc791af1...6f4a7396481ab28dd240cc7b1511949f1892ac2a)

TST: update maximum_inscribed_circle tests for latest GEOS changes

---

shapely/_geometry_helpers.pyx
shapely/tests/test_ragged_array.py

Fixes the issue reported in https://github.com/shapely/shapely/discussions/2284
We were allocating a too small temporary array for storing the intermediate rings.

BUG: avoid memory segfault in from_ragged_array

---

.github/workflows/release.yml
.github/workflows/tests.yml

The windows-2019 image was deprecated and now the builds were no longer running

CI: update windows-2019 to windows-2022

---

shapely/tests/test_measurement.py

This test is currently failing on the builds against GEOS main:
```
>       return lib.frechet_distance_densify(a, b, densify, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       shapely.errors.GEOSException: IllegalArgumentException: Fraction is not in range (0.001 - 1.0]
```
We were testing with exactly a densify fraction of 0.001, but a recent change in GEOS (https://github.com/libgeos/geos/commit/ae1f72600b5939169d57c1ae76cd9dec7fba847e#diff-a81958906dd1e0b8d7226c676d64f313b6c5ee44ea817a98731f0646b64153daL62-R97) changed the lower bound from 0 to 0.001.

TST: update frechet_distance densify test for latest GEOS main (densify>0.001)``

---

shapely/set_operations.py
shapely/tests/test_set_operations.py

Upstream GEOS recently changed so this now raises an error instead of silently returning the invalid input unchanged.
xref https://github.com/libgeos/geos/pull/1279#discussion_r2253380355

TST: update test_coverage_union_overlapping_inputs for upstream GEOS change
